//! Slate's semantic mapping for Zellij 0.45.1 component themes (KDL v1).
use crate::{error::Result, theme::ThemeVariant};
use std::fmt::Write;

pub(super) const HEADER: &str = "// Generated by Slate: Zellij theme (slate-sync)\n";

pub(super) fn render(theme: &ThemeVariant) -> Result<String> {
    theme.validate()?;
    let p = &theme.palette;
    let background = p.background.as_str();
    let foreground = p.foreground.as_str();
    let surface = p
        .surface0
        .as_deref()
        .or(p.bg_dim.as_deref())
        .unwrap_or(background);
    let selection = p.selection_bg.as_deref().unwrap_or(&p.blue);
    let contrast = |bg| {
        crate::wcag::pick_accessible_fg_for_bg(&[foreground, background, &p.black, &p.white], bg)
    };
    let selected_fg = contrast(selection);
    let ribbon_fg = contrast(&p.blue);
    let mut output = format!("{HEADER}themes {{\n    slate-sync {{\n");
    for (name, base, bg, emphasis) in [
        ("text_unselected", foreground, surface, false),
        ("text_selected", selected_fg.as_str(), selection, true),
        ("ribbon_unselected", foreground, surface, false),
        ("ribbon_selected", ribbon_fg.as_str(), p.blue.as_str(), true),
        ("table_title", p.cyan.as_str(), background, false),
        ("table_cell_unselected", foreground, background, false),
        ("table_cell_selected", selected_fg.as_str(), selection, true),
        ("list_unselected", foreground, background, false),
        ("list_selected", selected_fg.as_str(), selection, true),
        (
            "frame_unselected",
            p.bright_black.as_str(),
            background,
            false,
        ),
        ("frame_selected", p.blue.as_str(), background, false),
        ("frame_highlight", p.yellow.as_str(), background, false),
        ("exit_code_success", p.green.as_str(), background, false),
        ("exit_code_error", p.red.as_str(), background, false),
    ] {
        let _ = writeln!(
            output,
            "        {name} {{\n            base {base:?}\n            background {bg:?}"
        );
        for (index, color) in [&p.yellow, &p.cyan, &p.green, &p.magenta]
            .into_iter()
            .enumerate()
        {
            let color = if emphasis { base } else { color.as_str() };
            let _ = writeln!(output, "            emphasis_{index} {color:?}");
        }
        output.push_str("        }\n");
    }
    output.push_str("        multiplayer_user_colors {\n");
    for (index, color) in [
        &p.magenta,
        &p.blue,
        &p.green,
        &p.yellow,
        &p.cyan,
        &p.red,
        &p.bright_magenta,
        &p.bright_blue,
        &p.bright_green,
        &p.bright_cyan,
    ]
    .into_iter()
    .enumerate()
    {
        let _ = writeln!(output, "            player_{} {color:?}", index + 1);
    }
    output.push_str("        }\n    }\n}\n");
    Ok(output)
}
