use crate::{error::Result, theme::ThemeVariant};

pub(super) const HEADER: &str = "# Generated by Slate: btop theme (slate-sync)\n";

/// Complete btop 1.4.7 semantic palette, derived from every bundled Slate
/// theme. Lower-load graphs stay cool; temperature/load ends use warning/error.
pub(super) fn render(theme: &ThemeVariant) -> Result<String> {
    let p = &theme.palette;
    p.validate()?;
    let colors = [
        ("main_bg", &p.background),
        ("main_fg", &p.foreground),
        ("title", &p.foreground),
        ("hi_fg", &p.cyan),
        ("selected_bg", &p.blue),
        ("selected_fg", &p.background),
        ("inactive_fg", &p.bright_black),
        ("graph_text", &p.bright_black),
        ("meter_bg", &p.bright_black),
        ("proc_misc", &p.magenta),
        ("cpu_box", &p.blue),
        ("mem_box", &p.green),
        ("net_box", &p.magenta),
        ("proc_box", &p.cyan),
        ("div_line", &p.bright_black),
        ("temp_start", &p.green),
        ("temp_mid", &p.yellow),
        ("temp_end", &p.red),
        ("cpu_start", &p.cyan),
        ("cpu_mid", &p.yellow),
        ("cpu_end", &p.red),
        ("free_start", &p.green),
        ("free_mid", &p.green),
        ("free_end", &p.bright_green),
        ("cached_start", &p.magenta),
        ("cached_mid", &p.magenta),
        ("cached_end", &p.bright_magenta),
        ("available_start", &p.blue),
        ("available_mid", &p.cyan),
        ("available_end", &p.bright_cyan),
        ("used_start", &p.yellow),
        ("used_mid", &p.yellow),
        ("used_end", &p.red),
        ("download_start", &p.blue),
        ("download_mid", &p.cyan),
        ("download_end", &p.bright_cyan),
        ("upload_start", &p.magenta),
        ("upload_mid", &p.magenta),
        ("upload_end", &p.bright_magenta),
        ("process_start", &p.green),
        ("process_mid", &p.yellow),
        ("process_end", &p.red),
        ("proc_pause_bg", &p.red),
        ("proc_follow_bg", &p.blue),
        ("proc_banner_bg", &p.magenta),
        ("proc_banner_fg", &p.background),
        ("followed_bg", &p.blue),
        ("followed_fg", &p.background),
    ];
    let mut out = HEADER.to_owned();
    for (name, color) in colors {
        out.push_str(&format!("theme[{name}]=\"{color}\"\n"));
    }
    Ok(out)
}
