pub mod about;
pub(crate) mod apply;
pub mod aura;
pub mod auto_theme;
mod auto_theme_resolution;
pub mod clean;
pub mod config;
pub mod doctor;
pub mod failure_handler;
mod file_output;
pub mod font;
pub mod font_detection;
pub mod font_selection;
pub mod hub;
pub mod list;
mod menu;
mod ui_language;
pub use ui_language::load_saved_ui_language;
pub mod new_shell_reminder;
pub mod picker;
pub mod preflight;
pub mod preset_selection;
pub mod prompt;
pub mod recover;
pub mod restore;
pub mod set;
pub mod setup;
pub mod setup_executor;
pub mod share;
pub mod share_screenshot;
pub mod status;
pub mod status_panel;
pub mod theme;
pub mod theme_apply;
mod theme_handoff;
pub mod theme_selection;
pub mod tool_selection;
pub mod tools;
pub mod watch;
pub mod wizard_core;

mod startup_detection;
mod wizard_support;
