//! Read-only loader preparation before installers/theme writes. Publication is
//! atomic per file, not a transaction or exclusion of unrelated filesystem edits.
use crate::{
    adapter::marker_block,
    config::{
        file_read::{self, Links, Source, MAX_TOOL_CONFIG_BYTES},
        recovery_paths,
        state_files::atomic_write_synced_mode,
    },
    detection,
    env::SlateEnv,
    error::{Result, SlateError},
    platform::shell::{fish_quote, ShellBackend},
};
use std::path::{Path, PathBuf};

fn failure(path: &Path, reason: impl std::fmt::Display) -> SlateError {
    SlateError::ConfigWriteError(
        format!("{path:?}"),
        format!("Shell loader: {reason}; file contents omitted"),
    )
}

pub(super) struct PreparedShellLoader {
    shell: ShellBackend,
    managed: PathBuf,
    path: PathBuf,
    location: PathBuf,
    original: Option<Source>,
    desired: Vec<u8>,
}

fn selected_paths(env: &SlateEnv, shell: ShellBackend) -> Result<(PathBuf, PathBuf)> {
    let path = match shell {
        ShellBackend::Bash => env.bash_integration_path(),
        ShellBackend::Zsh => env.zshrc_path(),
        ShellBackend::Fish => env.fish_loader_path(),
        ShellBackend::Unsupported => {
            return Err(SlateError::PlatformError(
                "Slate shell integration currently targets zsh, bash, and fish only.".into(),
            ))
        }
    };
    Ok((
        path,
        env.config_dir()
            .join("managed/shell")
            .join(format!("env.{}", shell.label())),
    ))
}

impl PreparedShellLoader {
    pub(super) fn capture(env: &SlateEnv, shell: ShellBackend) -> Result<Self> {
        let (path, source) = selected_paths(env, shell)?;
        recovery_paths::validate_file_path(env, &path, "shell loader")?;
        let original = file_read::read(&path, MAX_TOOL_CONFIG_BYTES, Links::Reject)
            .map_err(|error| failure(&path, error))?;
        let desired = if shell == ShellBackend::Fish {
            let quoted = fish_quote(&source.to_string_lossy());
            format!("# Generated by slate - managed loader\nif test -f {quoted}\n  source {quoted}\nend\n").into_bytes()
        } else {
            let quoted = detection::shell_quote_path(&source);
            // .profile is also read by non-Bash shells. Keep the surrounding
            // file POSIX-parseable and only load Bash's generated environment
            // when the standard Bash version variable is present.
            let guard = if shell == ShellBackend::Bash && path == env.shell_profile_path() {
                "[ -n \"${BASH_VERSION:-}\" ] && "
            } else {
                ""
            };
            let block = format!(
                "{}\nif {guard}[ -f {quoted} ]; then\n  source {quoted}\nfi\n{}\n",
                marker_block::START,
                marker_block::END
            );
            marker_block::upsert_managed_block_bytes(
                original.as_ref().map_or(&[], |file| file.bytes.as_slice()),
                block.as_bytes(),
            )
            .map_err(|error| failure(&path, error))?
        };
        if desired.len() as u64 > MAX_TOOL_CONFIG_BYTES {
            return Err(failure(&path, "generated loader exceeds the 8 MiB limit"));
        }
        let location = file_read::directory_alias_target(&path)
            .ok_or_else(|| failure(&path, "cannot resolve parent directory"))?;
        Ok(Self {
            shell,
            managed: source,
            path,
            location,
            original,
            desired,
        })
    }

    pub(super) fn verify(&self, env: &SlateEnv) -> Result<()> {
        let (path, managed) = selected_paths(env, self.shell)?;
        if path != self.path || managed != self.managed {
            return Err(failure(&self.path, "selected startup or environment path changed after preparation; inspect the new selection and rerun setup"));
        }
        recovery_paths::validate_file_path(env, &self.path, "shell loader")?;
        let current = file_read::read(&self.path, MAX_TOOL_CONFIG_BYTES, Links::Reject)
            .map_err(|error| failure(&self.path, error))?;
        if current != self.original
            || file_read::directory_alias_target(&self.path).as_ref() != Some(&self.location)
        {
            return Err(failure(&self.path, "file or directory changed after preparation; inspect it and rerun setup without overwriting later edits"));
        }
        Ok(())
    }

    pub(super) fn publish(&self, env: &SlateEnv) -> Result<()> {
        self.verify(env)?;
        if self
            .original
            .as_ref()
            .is_some_and(|source| source.bytes == self.desired)
        {
            return Ok(());
        }
        let parent = self
            .path
            .parent()
            .ok_or_else(|| failure(&self.path, "no parent directory"))?;
        std::fs::create_dir_all(parent)?;
        self.verify(env)?;
        atomic_write_synced_mode(
            &self.path,
            &self.desired,
            self.original
                .as_ref()
                .and_then(|source| source.mode)
                .or(Some(0o600)),
        )
    }
}

#[cfg(test)]
mod tests;

#[cfg(test)]
mod bash_tests;
