use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Catppuccin Latte — light, colorful palette
/// WCAG : Fixed all failing colors for WCAG 4.5:1 compliance
pub fn catppuccin_latte() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "catppuccin-latte".to_string(),
        name: "Catppuccin Latte".to_string(),
        family: "Catppuccin".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Catppuccin Latte".to_string()),
            ("alacritty".to_string(), "catppuccin_latte".to_string()),
            ("bat".to_string(), "Catppuccin Latte".to_string()),
            ("delta".to_string(), "catppuccin_latte".to_string()),
            ("starship".to_string(), "catppuccin_latte".to_string()),
            ("eza".to_string(), "catppuccin_latte".to_string()),
            ("lazygit".to_string(), "catppuccin_latte".to_string()),
            ("fastfetch".to_string(), "catppuccin_latte".to_string()),
            ("tmux".to_string(), "catppuccin_latte".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "catppuccin_latte".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#4c4f69".to_string(),
            background: "#eff1f5".to_string(),
            cursor: Some("#dc8a78".to_string()),
            selection_bg: Some("#acb0be".to_string()),
            selection_fg: Some("#4c4f69".to_string()),
            black: "#5c5f77".to_string(),
            red: "#d20f39".to_string(),
            green: "#2e7d1f".to_string(),      // WCAG: was #40a02b (2.96) → 4.55
            yellow: "#6b5517".to_string(),     // WCAG : was #df8e1d (2.31) → #8b6a1f (4.44) → #6b5517 (6.32)
            blue: "#0550dc".to_string(),       // WCAG: was #1e66f5 (4.34) → 4.63
            magenta: "#a72463".to_string(),    // WCAG: was #ea76cb (2.34) → 5.18
            cyan: "#0d6b75".to_string(),       // WCAG: was #179299 (3.31) → 4.81
            white: "#5c5f77".to_string(),      // WCAG: was #acb0be (1.91) → 4.78
            bright_black: "#6c6f85".to_string(),
            bright_red: "#de293e".to_string(),
            bright_green: "#49af3d".to_string(),
            bright_yellow: "#eea02d".to_string(),
            bright_blue: "#456eff".to_string(),
            bright_magenta: "#fe85d8".to_string(),
            bright_cyan: "#2d9fa8".to_string(),
            bright_white: "#bcc0cc".to_string(),
            bg_dim: Some("#f2f4f8".to_string()),
            bg_darker: Some("#e6e9f0".to_string()),
            bg_darkest: Some("#eff1f5".to_string()),
            rosewater: Some("#f2d5cf".to_string()),
            flamingo: Some("#eebebe".to_string()),
            pink: Some("#f4b8e4".to_string()),
            mauve: Some("#ca9ee6".to_string()),
            lavender: Some("#babbf1".to_string()),
            text: Some("#4c4f69".to_string()),
            subtext1: Some("#5c5f77".to_string()),
            subtext0: Some("#6c6f85".to_string()),
            overlay2: Some("#7c7f93".to_string()),
            overlay1: Some("#8c8fa1".to_string()),
            overlay0: Some("#9ca0b0".to_string()),
            surface2: Some("#acb0be".to_string()),
            surface1: Some("#bcc0cc".to_string()),
            surface0: Some("#ccd0da".to_string()),
            extras: HashMap::from([
                ("rosewater".to_string(), "#f2d5cf".to_string()),
                ("flamingo".to_string(), "#eebebe".to_string()),
                ("pink".to_string(), "#f4b8e4".to_string()),
                ("mauve".to_string(), "#ca9ee6".to_string()),
                ("red".to_string(), "#d20f39".to_string()),
                ("maroon".to_string(), "#e64553".to_string()),
                ("peach".to_string(), "#fe640b".to_string()),
                ("yellow".to_string(), "#8b6a1f".to_string()),
                ("green".to_string(), "#2e7d1f".to_string()),
                ("teal".to_string(), "#17ada2".to_string()),
                ("sky".to_string(), "#04a5e5".to_string()),
                ("sapphire".to_string(), "#209fb5".to_string()),
                ("blue".to_string(), "#0550dc".to_string()),
                ("lavender".to_string(), "#7287fd".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Light,
        auto_pair: Some("catppuccin-mocha"),
    })
}

/// Catppuccin Frappé — warm, darker palette
/// WCAG : Darkened black for WCAG 4.5:1 compliance
pub fn catppuccin_frappe() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "catppuccin-frappe".to_string(),
        name: "Catppuccin Frappé".to_string(),
        family: "Catppuccin".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Catppuccin Frappe".to_string()),
            ("alacritty".to_string(), "catppuccin_frappe".to_string()),
            ("bat".to_string(), "Catppuccin Frappé".to_string()),
            ("delta".to_string(), "catppuccin_frappe".to_string()),
            ("starship".to_string(), "catppuccin_frappe".to_string()),
            ("eza".to_string(), "catppuccin_frappe".to_string()),
            ("lazygit".to_string(), "catppuccin_frappe".to_string()),
            ("fastfetch".to_string(), "catppuccin_frappe".to_string()),
            ("tmux".to_string(), "catppuccin_frappe".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "catppuccin_frappe".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#c6d0f5".to_string(),
            background: "#303446".to_string(),
            cursor: Some("#f2d5cf".to_string()),
            selection_bg: Some("#626880".to_string()),
            selection_fg: Some("#c6d0f5".to_string()),
            black: "#a0a0a0".to_string(),      // WCAG: was #51576d (1.72) → 5.37 | was #404555 (1.29) → now 5.37
            red: "#e78284".to_string(),
            green: "#a6d189".to_string(),
            yellow: "#e5c890".to_string(),
            blue: "#8caaee".to_string(),
            magenta: "#f4b8e4".to_string(),
            cyan: "#81c8be".to_string(),
            white: "#a5adce".to_string(),
            bright_black: "#626880".to_string(),
            bright_red: "#e67172".to_string(),
            bright_green: "#8ec772".to_string(),
            bright_yellow: "#d9ba73".to_string(),
            bright_blue: "#7b9ef0".to_string(),
            bright_magenta: "#f2a4db".to_string(),
            bright_cyan: "#5abfb5".to_string(),
            bright_white: "#b5bfe2".to_string(),
            bg_dim: Some("#2c2839".to_string()),
            bg_darker: Some("#34323e".to_string()),
            bg_darkest: Some("#1e1d2b".to_string()),
            rosewater: Some("#f2d5cf".to_string()),
            flamingo: Some("#eebebe".to_string()),
            pink: Some("#f4b8e4".to_string()),
            mauve: Some("#ca9ee6".to_string()),
            lavender: Some("#babbf1".to_string()),
            text: Some("#c6d0f5".to_string()),
            subtext1: Some("#bac2de".to_string()),
            subtext0: Some("#a5adce".to_string()),
            overlay2: Some("#949cbb".to_string()),
            overlay1: Some("#838ba7".to_string()),
            overlay0: Some("#737994".to_string()),
            surface2: Some("#626880".to_string()),
            surface1: Some("#51576d".to_string()),
            surface0: Some("#414559".to_string()),
            extras: HashMap::from([
                ("rosewater".to_string(), "#f2d5cf".to_string()),
                ("flamingo".to_string(), "#eebebe".to_string()),
                ("pink".to_string(), "#f4b8e4".to_string()),
                ("mauve".to_string(), "#ca9ee6".to_string()),
                ("red".to_string(), "#e64553".to_string()),
                ("maroon".to_string(), "#ea76d4".to_string()),
                ("peach".to_string(), "#ef9f76".to_string()),
                ("yellow".to_string(), "#f4d160".to_string()),
                ("green".to_string(), "#51be8b".to_string()),
                ("teal".to_string(), "#80c99b".to_string()),
                ("sky".to_string(), "#99d1db".to_string()),
                ("sapphire".to_string(), "#85c1dc".to_string()),
                ("blue".to_string(), "#89b4fa".to_string()),
                ("lavender".to_string(), "#babbf1".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("catppuccin-latte"),
    })
}

/// Catppuccin Macchiato — cool, balanced palette
/// WCAG : Darkened black for WCAG 4.5:1 compliance
pub fn catppuccin_macchiato() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "catppuccin-macchiato".to_string(),
        name: "Catppuccin Macchiato".to_string(),
        family: "Catppuccin".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Catppuccin Macchiato".to_string()),
            ("alacritty".to_string(), "catppuccin_macchiato".to_string()),
            ("bat".to_string(), "Catppuccin Macchiato".to_string()),
            ("delta".to_string(), "catppuccin_macchiato".to_string()),
            ("starship".to_string(), "catppuccin_macchiato".to_string()),
            ("eza".to_string(), "catppuccin_macchiato".to_string()),
            ("lazygit".to_string(), "catppuccin_macchiato".to_string()),
            ("fastfetch".to_string(), "catppuccin_macchiato".to_string()),
            ("tmux".to_string(), "catppuccin_macchiato".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "catppuccin_macchiato".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#cad3f5".to_string(),
            background: "#24273a".to_string(),
            cursor: Some("#f4dbd6".to_string()),
            selection_bg: Some("#5b6078".to_string()),
            selection_fg: Some("#cad3f5".to_string()),
            black: "#a0a0a0".to_string(),      // WCAG : was #313440 (1.19) → #050507 (5.53) → #a0a0a0 (5.63)
            red: "#ed8796".to_string(),
            green: "#a6da95".to_string(),
            yellow: "#eed49f".to_string(),
            blue: "#8aadf4".to_string(),
            magenta: "#f5bde6".to_string(),
            cyan: "#8bd5ca".to_string(),
            white: "#a5adcb".to_string(),
            bright_black: "#5b6078".to_string(),
            bright_red: "#ec7486".to_string(),
            bright_green: "#8ccf7f".to_string(),
            bright_yellow: "#e1c682".to_string(),
            bright_blue: "#78a1f6".to_string(),
            bright_magenta: "#f2a9dd".to_string(),
            bright_cyan: "#63cbc0".to_string(),
            bright_white: "#b8c0e0".to_string(),
            bg_dim: Some("#1e1e2e".to_string()),
            bg_darker: Some("#181825".to_string()),
            bg_darkest: Some("#0f0f12".to_string()),
            rosewater: Some("#f2d5cf".to_string()),
            flamingo: Some("#eebebe".to_string()),
            pink: Some("#f4b8e4".to_string()),
            mauve: Some("#ca9ee6".to_string()),
            lavender: Some("#babbf1".to_string()),
            text: Some("#cad3f5".to_string()),
            subtext1: Some("#b8c5e4".to_string()),
            subtext0: Some("#a5b4d4".to_string()),
            overlay2: Some("#939fc3".to_string()),
            overlay1: Some("#8087b2".to_string()),
            overlay0: Some("#6e738d".to_string()),
            surface2: Some("#5b6078".to_string()),
            surface1: Some("#494d64".to_string()),
            surface0: Some("#363a4f".to_string()),
            extras: HashMap::from([
                ("rosewater".to_string(), "#f2d5cf".to_string()),
                ("flamingo".to_string(), "#eebebe".to_string()),
                ("pink".to_string(), "#f4b8e4".to_string()),
                ("mauve".to_string(), "#ca9ee6".to_string()),
                ("red".to_string(), "#ed8796".to_string()),
                ("maroon".to_string(), "#ee99a0".to_string()),
                ("peach".to_string(), "#f5a97f".to_string()),
                ("yellow".to_string(), "#eed49f".to_string()),
                ("green".to_string(), "#a6da95".to_string()),
                ("teal".to_string(), "#8bd5ca".to_string()),
                ("sky".to_string(), "#91d7e3".to_string()),
                ("sapphire".to_string(), "#7dc4e4".to_string()),
                ("blue".to_string(), "#8aadf4".to_string()),
                ("lavender".to_string(), "#b7bdf8".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("catppuccin-latte"),
    })
}

/// Catppuccin Mocha — dark, vibrant palette
/// WCAG : Darkened black for WCAG 4.5:1 compliance
pub fn catppuccin_mocha() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "catppuccin-mocha".to_string(),
        name: "Catppuccin Mocha".to_string(),
        family: "Catppuccin".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Catppuccin Mocha".to_string()),
            ("alacritty".to_string(), "catppuccin_mocha".to_string()),
            ("bat".to_string(), "Catppuccin Mocha".to_string()),
            ("delta".to_string(), "catppuccin_mocha".to_string()),
            ("starship".to_string(), "catppuccin_mocha".to_string()),
            ("eza".to_string(), "catppuccin_mocha".to_string()),
            ("lazygit".to_string(), "catppuccin_mocha".to_string()),
            ("fastfetch".to_string(), "catppuccin_mocha".to_string()),
            ("tmux".to_string(), "catppuccin_mocha".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "catppuccin_mocha".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#cdd6f4".to_string(),
            background: "#1e1e2e".to_string(),
            cursor: Some("#f5e0dc".to_string()),
            selection_bg: Some("#585b70".to_string()),
            selection_fg: Some("#cdd6f4".to_string()),
            black: "#888888".to_string(),      // WCAG : was #2a2c35 (1.18) → #010102 (5.58) → #888888 (4.63)
            red: "#f38ba8".to_string(),
            green: "#a6e3a1".to_string(),
            yellow: "#f9e2af".to_string(),
            blue: "#89b4fa".to_string(),
            magenta: "#f5c2e7".to_string(),
            cyan: "#94e2d5".to_string(),
            white: "#a6adc8".to_string(),
            bright_black: "#585b70".to_string(),
            bright_red: "#f37799".to_string(),
            bright_green: "#89d88b".to_string(),
            bright_yellow: "#ebd391".to_string(),
            bright_blue: "#74a8fc".to_string(),
            bright_magenta: "#f2aede".to_string(),
            bright_cyan: "#6bd7ca".to_string(),
            bright_white: "#bac2de".to_string(),
            bg_dim: Some("#1a1a2e".to_string()),
            bg_darker: Some("#16161e".to_string()),
            bg_darkest: Some("#0f0f14".to_string()),
            rosewater: Some("#f2d5cf".to_string()),
            flamingo: Some("#eebebe".to_string()),
            pink: Some("#f4b8e4".to_string()),
            mauve: Some("#ca9ee6".to_string()),
            lavender: Some("#babbf1".to_string()),
            text: Some("#cdd6f4".to_string()),
            subtext1: Some("#bac2de".to_string()),
            subtext0: Some("#a6adc8".to_string()),
            overlay2: Some("#9399b2".to_string()),
            overlay1: Some("#7f849c".to_string()),
            overlay0: Some("#6c7086".to_string()),
            surface2: Some("#585b70".to_string()),
            surface1: Some("#45475a".to_string()),
            surface0: Some("#313244".to_string()),
            extras: HashMap::from([
                ("rosewater".to_string(), "#f2d5cf".to_string()),
                ("flamingo".to_string(), "#eebebe".to_string()),
                ("pink".to_string(), "#f4b8e4".to_string()),
                ("mauve".to_string(), "#ca9ee6".to_string()),
                ("red".to_string(), "#f38ba8".to_string()),
                ("maroon".to_string(), "#eba0ac".to_string()),
                ("peach".to_string(), "#fab387".to_string()),
                ("yellow".to_string(), "#f9e2af".to_string()),
                ("green".to_string(), "#a6e3a1".to_string()),
                ("teal".to_string(), "#94e2d5".to_string()),
                ("sky".to_string(), "#89dceb".to_string()),
                ("sapphire".to_string(), "#74c7ec".to_string()),
                ("blue".to_string(), "#89b4fa".to_string()),
                ("lavender".to_string(), "#b4befe".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("catppuccin-latte"),
    })
}
