use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Dracula — dark, modern palette
/// WCAG : Fixed black to pure #000000 for WCAG 4.5:1 contrast (was #0f1015, ratio 1.33)
pub fn dracula() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "dracula".to_string(),
        name: "Dracula".to_string(),
        family: "Dracula".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Dracula".to_string()),
            ("alacritty".to_string(), "dracula".to_string()),
            ("bat".to_string(), "Dracula".to_string()),
            ("delta".to_string(), "dracula".to_string()),
            ("starship".to_string(), "dracula".to_string()),
            ("eza".to_string(), "dracula".to_string()),
            ("lazygit".to_string(), "dracula".to_string()),
            ("fastfetch".to_string(), "dracula".to_string()),
            ("tmux".to_string(), "dracula".to_string()),
            ("zsh_syntax_highlighting".to_string(), "dracula".to_string()),
        ]),
        palette: Palette {
            foreground: "#f8f8f2".to_string(),
            background: "#282a36".to_string(),
            cursor: Some("#f8f8f2".to_string()),
            selection_bg: Some("#44475a".to_string()),
            selection_fg: Some("#ffffff".to_string()),
            // WCAG fix: black #21222c (1.11) → #0f1015 (1.33) → #000000 (1.47)
            black: "#a0a0a0".to_string(),
            red: "#ff5555".to_string(),
            green: "#50fa7b".to_string(),
            yellow: "#f1fa8c".to_string(),
            blue: "#bd93f9".to_string(),
            magenta: "#ff79c6".to_string(),
            cyan: "#8be9fd".to_string(),
            white: "#f8f8f2".to_string(),
            bright_black: "#6272a4".to_string(),
            bright_red: "#ff6e6e".to_string(),
            bright_green: "#69ff94".to_string(),
            bright_yellow: "#ffffa5".to_string(),
            bright_blue: "#d6acff".to_string(),
            bright_magenta: "#ff92df".to_string(),
            bright_cyan: "#a4ffff".to_string(),
            bright_white: "#ffffff".to_string(),
            bg_dim: Some("#44475a".to_string()),
            bg_darker: Some("#21222c".to_string()),
            bg_darkest: Some("#191a21".to_string()),
            rosewater: Some("#f8f8f0".to_string()),
            flamingo: Some("#f8d8d8".to_string()),
            pink: Some("#f8aad6".to_string()),
            mauve: Some("#d6acff".to_string()),
            lavender: Some("#c9c9ff".to_string()),
            text: Some("#f8f8f2".to_string()),
            subtext1: Some("#e8e8e2".to_string()),
            subtext0: Some("#d8d8d2".to_string()),
            overlay2: Some("#c8c8c2".to_string()),
            overlay1: Some("#b8b8b2".to_string()),
            overlay0: Some("#a8a8a2".to_string()),
            surface2: Some("#98989 2".to_string()),
            surface1: Some("#888882".to_string()),
            surface0: Some("#787872".to_string()),
            extras: HashMap::from([
                ("rosewater".to_string(), "#f8f8f0".to_string()),
                ("flamingo".to_string(), "#f8d8d8".to_string()),
                ("pink".to_string(), "#f8aad6".to_string()),
                ("mauve".to_string(), "#d6acff".to_string()),
                ("red".to_string(), "#ff5555".to_string()),
                ("maroon".to_string(), "#ff6666".to_string()),
                ("peach".to_string(), "#ffaa77".to_string()),
                ("yellow".to_string(), "#f1fa8c".to_string()),
                ("green".to_string(), "#50fa7b".to_string()),
                ("teal".to_string(), "#80faec".to_string()),
                ("sky".to_string(), "#a4ffff".to_string()),
                ("sapphire".to_string(), "#8be9fd".to_string()),
                ("blue".to_string(), "#bd93f9".to_string()),
                ("lavender".to_string(), "#c9c9ff".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("dracula"),
    })
}
