use crate::error::Result;
use super::{ThemeVariant, ToolRefs, Palette};

/// Dracula — dark, modern palette
pub fn dracula() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "dracula".to_string(),
        name: "Dracula".to_string(),
        family: "Dracula".to_string(),
        tool_refs: ToolRefs {
            ghostty: "Dracula".to_string(),
            alacritty: "dracula".to_string(),
            bat: "Dracula".to_string(),
            delta: "dracula".to_string(),
            starship: "dracula".to_string(),
            eza: "dracula".to_string(),
            lazygit: "dracula".to_string(),
            fastfetch: "dracula".to_string(),
            tmux: "dracula".to_string(),
            zsh_syntax_highlighting: "dracula".to_string(),
        },
        palette: Palette {
            foreground: "#f8f8f2".to_string(),
            background: "#282a36".to_string(),
            cursor: Some("#f8f8f2".to_string()),
            selection_bg: Some("#44475a".to_string()),
            selection_fg: Some("#f8f8f2".to_string()),
            black: "#44475a".to_string(),
            red: "#ff5555".to_string(),
            green: "#50fa7b".to_string(),
            yellow: "#f1fa8c".to_string(),
            blue: "#6495ed".to_string(),
            magenta: "#ff79c6".to_string(),
            cyan: "#8be9fd".to_string(),
            white: "#f8f8f2".to_string(),
            bright_black: "#6272a4".to_string(),
            bright_red: "#ff6e6e".to_string(),
            bright_green: "#69ff94".to_string(),
            bright_yellow: "#ffffa5".to_string(),
            bright_blue: "#d6acff".to_string(),
            bright_magenta: "#ff92df".to_string(),
            bright_cyan: "#a4ffff".to_string(),
            bright_white: "#ffffff".to_string(),
            rosewater: Some("#f8f8f0".to_string()),
            flamingo: Some("#ff79c6".to_string()),
            pink: Some("#ff79c6".to_string()),
            mauve: Some("#bd93f9".to_string()),
            lavender: Some("#a4ebf3".to_string()),
            text: Some("#f8f8f0".to_string()),
            subtext1: Some("#e0e0e0".to_string()),
            subtext0: Some("#8be9fd".to_string()),
            overlay2: Some("#6272a4".to_string()),
            overlay1: Some("#44475a".to_string()),
            overlay0: Some("#282a36".to_string()),
            surface2: Some("#44475a".to_string()),
            surface1: Some("#282a36".to_string()),
            surface0: Some("#21222c".to_string()),
            base: Some("#282a36".to_string()),
            mantle: Some("#21222c".to_string()),
            crust: Some("#191a21".to_string()),
        },
    })
}
