use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Everforest Dark — dark, nature-inspired palette
/// https://github.com/sainnhe/everforest
pub fn everforest_dark() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "everforest-dark".to_string(),
        name: "Everforest Dark".to_string(),
        family: "Everforest".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Everforest Dark".to_string()),
            ("alacritty".to_string(), "everforest_dark".to_string()),
            ("bat".to_string(), "Everforest Dark".to_string()),
            ("delta".to_string(), "everforest_dark".to_string()),
            ("starship".to_string(), "everforest_dark".to_string()),
            ("eza".to_string(), "everforest_dark".to_string()),
            ("lazygit".to_string(), "everforest_dark".to_string()),
            ("fastfetch".to_string(), "everforest_dark".to_string()),
            ("tmux".to_string(), "everforest_dark".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "everforest_dark".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#d4be98".to_string(),
            background: "#2b3339".to_string(),
            cursor: Some("#a9b665".to_string()),
            selection_bg: Some("#3d4949".to_string()),
            selection_fg: Some("#d4be98".to_string()),
            black: "#2b3339".to_string(),
            red: "#ea6962".to_string(),
            green: "#a9b665".to_string(),
            yellow: "#d8b356".to_string(),
            blue: "#7daea3".to_string(),
            magenta: "#d3869b".to_string(),
            cyan: "#89b482".to_string(),
            white: "#d4be98".to_string(),
            bright_black: "#504945".to_string(),
            bright_red: "#ea6962".to_string(),
            bright_green: "#a9b665".to_string(),
            bright_yellow: "#d8b356".to_string(),
            bright_blue: "#7daea3".to_string(),
            bright_magenta: "#d3869b".to_string(),
            bright_cyan: "#89b482".to_string(),
            bright_white: "#d4be98".to_string(),
            bg_dim: Some("#323c41".to_string()),
            bg_darker: Some("#2d3139".to_string()),
            bg_darkest: Some("#2b3339".to_string()),
            rosewater: None,
            flamingo: None,
            pink: None,
            mauve: None,
            lavender: None,
            text: Some("#d4be98".to_string()),
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
            extras: HashMap::from([
                ("red".to_string(), "#ea6962".to_string()),
                ("orange".to_string(), "#e78a4e".to_string()),
                ("yellow".to_string(), "#d8b356".to_string()),
                ("green".to_string(), "#a9b665".to_string()),
                ("blue".to_string(), "#7daea3".to_string()),
                ("purple".to_string(), "#d3869b".to_string()),
                ("cyan".to_string(), "#89b482".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("everforest-light"),
    })
}

/// Everforest Light — light, earthy palette
/// https://github.com/sainnhe/everforest
pub fn everforest_light() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "everforest-light".to_string(),
        name: "Everforest Light".to_string(),
        family: "Everforest".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Everforest Light".to_string()),
            ("alacritty".to_string(), "everforest_light".to_string()),
            ("bat".to_string(), "Everforest Light".to_string()),
            ("delta".to_string(), "everforest_light".to_string()),
            ("starship".to_string(), "everforest_light".to_string()),
            ("eza".to_string(), "everforest_light".to_string()),
            ("lazygit".to_string(), "everforest_light".to_string()),
            ("fastfetch".to_string(), "everforest_light".to_string()),
            ("tmux".to_string(), "everforest_light".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "everforest_light".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#5c6a72".to_string(),
            background: "#fffbef".to_string(),
            cursor: Some("#9a8c59".to_string()),
            selection_bg: Some("#f5ede0".to_string()),
            selection_fg: Some("#5c6a72".to_string()),
            black: "#fffbef".to_string(),
            red: "#f85552".to_string(),
            green: "#8da101".to_string(),
            yellow: "#cc8737".to_string(),
            blue: "#669fbc".to_string(),
            magenta: "#b280a0".to_string(),
            cyan: "#66985d".to_string(),
            white: "#5c6a72".to_string(),
            bright_black: "#bdae93".to_string(),
            bright_red: "#f85552".to_string(),
            bright_green: "#8da101".to_string(),
            bright_yellow: "#cc8737".to_string(),
            bright_blue: "#669fbc".to_string(),
            bright_magenta: "#b280a0".to_string(),
            bright_cyan: "#66985d".to_string(),
            bright_white: "#5c6a72".to_string(),
            bg_dim: Some("#fdfaf5".to_string()),
            bg_darker: Some("#faf7f2".to_string()),
            bg_darkest: Some("#fffbef".to_string()),
            rosewater: None,
            flamingo: None,
            pink: None,
            mauve: None,
            lavender: None,
            text: Some("#5c6a72".to_string()),
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
            extras: HashMap::from([
                ("red".to_string(), "#f85552".to_string()),
                ("orange".to_string(), "#f08d49".to_string()),
                ("yellow".to_string(), "#cc8737".to_string()),
                ("green".to_string(), "#8da101".to_string()),
                ("blue".to_string(), "#669fbc".to_string()),
                ("purple".to_string(), "#b280a0".to_string()),
                ("cyan".to_string(), "#66985d".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Light,
        auto_pair: Some("everforest-dark"),
    })
}
