use crate::error::Result;
use super::{ThemeVariant, ToolRefs, Palette};

/// Gruvbox Dark — warm, dark palette inspired by classic Vim colorscheme
pub fn gruvbox_dark() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "gruvbox-dark".to_string(),
        name: "Gruvbox Dark".to_string(),
        family: "Gruvbox".to_string(),
        tool_refs: ToolRefs {
            ghostty: "Gruvbox Dark".to_string(),
            alacritty: "gruvbox_dark".to_string(),
            bat: "Gruvbox Dark".to_string(),
            delta: "gruvbox_dark".to_string(),
            starship: "gruvbox_dark".to_string(),
            eza: "gruvbox_dark".to_string(),
            lazygit: "gruvbox_dark".to_string(),
            fastfetch: "gruvbox_dark".to_string(),
            tmux: "gruvbox_dark".to_string(),
            zsh_syntax_highlighting: "gruvbox_dark".to_string(),
        },
        palette: Palette {
            foreground: "#ebdbb2".to_string(),
            background: "#282828".to_string(),
            cursor: Some("#ebdbb2".to_string()),
            selection_bg: Some("#504945".to_string()),
            selection_fg: Some("#ebdbb2".to_string()),
            black: "#282828".to_string(),
            red: "#cc241d".to_string(),
            green: "#98971a".to_string(),
            yellow: "#d79921".to_string(),
            blue: "#458588".to_string(),
            magenta: "#b16286".to_string(),
            cyan: "#689d6a".to_string(),
            white: "#a89984".to_string(),
            bright_black: "#928374".to_string(),
            bright_red: "#fb4934".to_string(),
            bright_green: "#b8bb26".to_string(),
            bright_yellow: "#fabd2f".to_string(),
            bright_blue: "#83a598".to_string(),
            bright_magenta: "#d3869b".to_string(),
            bright_cyan: "#8ec07c".to_string(),
            bright_white: "#ebdbb2".to_string(),
            rosewater: None,
            flamingo: None,
            pink: None,
            mauve: None,
            lavender: None,
            text: None,
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
        },
    })
}

/// Gruvbox Light — warm, light palette inspired by classic Vim colorscheme
pub fn gruvbox_light() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "gruvbox-light".to_string(),
        name: "Gruvbox Light".to_string(),
        family: "Gruvbox".to_string(),
        tool_refs: ToolRefs {
            ghostty: "Gruvbox Light".to_string(),
            alacritty: "gruvbox_light".to_string(),
            bat: "Gruvbox Light".to_string(),
            delta: "gruvbox_light".to_string(),
            starship: "gruvbox_light".to_string(),
            eza: "gruvbox_light".to_string(),
            lazygit: "gruvbox_light".to_string(),
            fastfetch: "gruvbox_light".to_string(),
            tmux: "gruvbox_light".to_string(),
            zsh_syntax_highlighting: "gruvbox_light".to_string(),
        },
        palette: Palette {
            foreground: "#3c3836".to_string(),
            background: "#fbf1c7".to_string(),
            cursor: Some("#3c3836".to_string()),
            selection_bg: Some("#d5c4a1".to_string()),
            selection_fg: Some("#3c3836".to_string()),
            black: "#fbf1c7".to_string(),
            red: "#cc241d".to_string(),
            green: "#98971a".to_string(),
            yellow: "#d79921".to_string(),
            blue: "#458588".to_string(),
            magenta: "#b16286".to_string(),
            cyan: "#689d6a".to_string(),
            white: "#7c6f64".to_string(),
            bright_black: "#928374".to_string(),
            bright_red: "#9d0006".to_string(),
            bright_green: "#79740e".to_string(),
            bright_yellow: "#b57614".to_string(),
            bright_blue: "#076678".to_string(),
            bright_magenta: "#8f3f71".to_string(),
            bright_cyan: "#427b58".to_string(),
            bright_white: "#3c3836".to_string(),
            rosewater: None,
            flamingo: None,
            pink: None,
            mauve: None,
            lavender: None,
            text: None,
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
        },
    })
}
