use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Gruvbox Dark — warm, dark palette inspired by classic Vim colorscheme
pub fn gruvbox_dark() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "gruvbox-dark".to_string(),
        name: "Gruvbox Dark".to_string(),
        family: "Gruvbox".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Gruvbox Dark".to_string()),
            ("alacritty".to_string(), "gruvbox_dark".to_string()),
            ("bat".to_string(), "Gruvbox Dark".to_string()),
            ("delta".to_string(), "gruvbox_dark".to_string()),
            ("starship".to_string(), "gruvbox_dark".to_string()),
            ("eza".to_string(), "gruvbox_dark".to_string()),
            ("lazygit".to_string(), "gruvbox_dark".to_string()),
            ("fastfetch".to_string(), "gruvbox_dark".to_string()),
            ("tmux".to_string(), "gruvbox_dark".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "gruvbox_dark".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#ebdbb2".to_string(),
            background: "#282828".to_string(),
            cursor: Some("#ebdbb2".to_string()),
            selection_bg: Some("#504945".to_string()),
            selection_fg: Some("#ebdbb2".to_string()),
            black: "#282828".to_string(),
            red: "#cc241d".to_string(),
            green: "#98971a".to_string(),
            yellow: "#d79921".to_string(),
            blue: "#458588".to_string(),
            magenta: "#b16286".to_string(),
            cyan: "#689d6a".to_string(),
            white: "#a89984".to_string(),
            bright_black: "#928374".to_string(),
            bright_red: "#fb4934".to_string(),
            bright_green: "#b8bb26".to_string(),
            bright_yellow: "#fabd2f".to_string(),
            bright_blue: "#83a598".to_string(),
            bright_magenta: "#d3869b".to_string(),
            bright_cyan: "#8ec07c".to_string(),
            bright_white: "#ebdbb2".to_string(),
            bg_dim: Some("#32302f".to_string()),
            bg_darker: Some("#282828".to_string()),
            bg_darkest: Some("#1d2021".to_string()),
            rosewater: Some("#ebdbb2".to_string()),
            flamingo: Some("#d75f5f".to_string()),
            pink: Some("#d75f5f".to_string()),
            mauve: Some("#b16286".to_string()),
            lavender: Some("#83a598".to_string()),
            text: Some("#ebdbb2".to_string()),
            subtext1: Some("#d5c4a1".to_string()),
            subtext0: Some("#928374".to_string()),
            overlay2: Some("#a89984".to_string()),
            overlay1: Some("#7c6f64".to_string()),
            overlay0: Some("#504945".to_string()),
            surface2: Some("#7c6f64".to_string()),
            surface1: Some("#504945".to_string()),
            surface0: Some("#282828".to_string()),
            extras: HashMap::new(),
        },
    })
}

/// Gruvbox Light — warm, light palette inspired by classic Vim colorscheme
pub fn gruvbox_light() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "gruvbox-light".to_string(),
        name: "Gruvbox Light".to_string(),
        family: "Gruvbox".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Gruvbox Light".to_string()),
            ("alacritty".to_string(), "gruvbox_light".to_string()),
            ("bat".to_string(), "Gruvbox Light".to_string()),
            ("delta".to_string(), "gruvbox_light".to_string()),
            ("starship".to_string(), "gruvbox_light".to_string()),
            ("eza".to_string(), "gruvbox_light".to_string()),
            ("lazygit".to_string(), "gruvbox_light".to_string()),
            ("fastfetch".to_string(), "gruvbox_light".to_string()),
            ("tmux".to_string(), "gruvbox_light".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "gruvbox_light".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#3c3836".to_string(),
            background: "#fbf1c7".to_string(),
            cursor: Some("#3c3836".to_string()),
            selection_bg: Some("#d5c4a1".to_string()),
            selection_fg: Some("#3c3836".to_string()),
            black: "#fbf1c7".to_string(),
            red: "#cc241d".to_string(),
            green: "#98971a".to_string(),
            yellow: "#d79921".to_string(),
            blue: "#458588".to_string(),
            magenta: "#b16286".to_string(),
            cyan: "#689d6a".to_string(),
            white: "#7c6f64".to_string(),
            bright_black: "#928374".to_string(),
            bright_red: "#9d0006".to_string(),
            bright_green: "#79740e".to_string(),
            bright_yellow: "#b57614".to_string(),
            bright_blue: "#076678".to_string(),
            bright_magenta: "#8f3f71".to_string(),
            bright_cyan: "#427b58".to_string(),
            bright_white: "#3c3836".to_string(),
            bg_dim: Some("#f4f1de".to_string()),
            bg_darker: Some("#fbf1c7".to_string()),
            bg_darkest: Some("#f9f5d9".to_string()),
            rosewater: Some("#282828".to_string()),
            flamingo: Some("#cc241d".to_string()),
            pink: Some("#cc241d".to_string()),
            mauve: Some("#8f3f71".to_string()),
            lavender: Some("#076678".to_string()),
            text: Some("#282828".to_string()),
            subtext1: Some("#504945".to_string()),
            subtext0: Some("#a89984".to_string()),
            overlay2: Some("#9d8374".to_string()),
            overlay1: Some("#bdae93".to_string()),
            overlay0: Some("#d4c4a1".to_string()),
            surface2: Some("#bdae93".to_string()),
            surface1: Some("#d4c4a1".to_string()),
            surface0: Some("#f4f1de".to_string()),
            extras: HashMap::new(),
        },
    })
}
