use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Kanagawa Wave — dark, Japanese ukiyo-e aesthetic
/// https://github.com/rebelot/kanagawa.nvim
pub fn kanagawa_wave() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "kanagawa-wave".to_string(),
        name: "Kanagawa Wave".to_string(),
        family: "Kanagawa".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Kanagawa Wave".to_string()),
            ("alacritty".to_string(), "kanagawa_wave".to_string()),
            ("bat".to_string(), "Kanagawa Wave".to_string()),
            ("delta".to_string(), "kanagawa_wave".to_string()),
            ("starship".to_string(), "kanagawa_wave".to_string()),
            ("eza".to_string(), "kanagawa_wave".to_string()),
            ("lazygit".to_string(), "kanagawa_wave".to_string()),
            ("fastfetch".to_string(), "kanagawa_wave".to_string()),
            ("tmux".to_string(), "kanagawa_wave".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "kanagawa_wave".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#dcd7ba".to_string(),
            background: "#1f1f28".to_string(),
            cursor: Some("#d27e99".to_string()),
            selection_bg: Some("#2d4f45".to_string()),
            selection_fg: Some("#dcd7ba".to_string()),
            black: "#1f1f28".to_string(),
            red: "#c34043".to_string(),
            green: "#7aa89f".to_string(),
            yellow: "#8a8c3b".to_string(),
            blue: "#658594".to_string(),
            magenta: "#9cabca".to_string(),
            cyan: "#7aa89f".to_string(),
            white: "#dcd7ba".to_string(),
            bright_black: "#464646".to_string(),
            bright_red: "#d97000".to_string(),
            bright_green: "#7aa89f".to_string(),
            bright_yellow: "#8a8c3b".to_string(),
            bright_blue: "#658594".to_string(),
            bright_magenta: "#9cabca".to_string(),
            bright_cyan: "#7aa89f".to_string(),
            bright_white: "#dcd7ba".to_string(),
            bg_dim: Some("#223249".to_string()),
            bg_darker: Some("#16161d".to_string()),
            bg_darkest: Some("#0d0c0c".to_string()),
            rosewater: None,
            flamingo: None,
            pink: Some("#d27e99".to_string()),
            mauve: None,
            lavender: None,
            text: Some("#dcd7ba".to_string()),
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
            extras: HashMap::from([
                ("red".to_string(), "#c34043".to_string()),
                ("orange".to_string(), "#d97000".to_string()),
                ("yellow".to_string(), "#8a8c3b".to_string()),
                ("green".to_string(), "#7aa89f".to_string()),
                ("blue".to_string(), "#658594".to_string()),
                ("purple".to_string(), "#9cabca".to_string()),
                ("pink".to_string(), "#d27e99".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("kanagawa-lotus"),
    })
}

/// Kanagawa Dragon — dark, deeper variant
/// https://github.com/rebelot/kanagawa.nvim
pub fn kanagawa_dragon() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "kanagawa-dragon".to_string(),
        name: "Kanagawa Dragon".to_string(),
        family: "Kanagawa".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Kanagawa Dragon".to_string()),
            ("alacritty".to_string(), "kanagawa_dragon".to_string()),
            ("bat".to_string(), "Kanagawa Dragon".to_string()),
            ("delta".to_string(), "kanagawa_dragon".to_string()),
            ("starship".to_string(), "kanagawa_dragon".to_string()),
            ("eza".to_string(), "kanagawa_dragon".to_string()),
            ("lazygit".to_string(), "kanagawa_dragon".to_string()),
            ("fastfetch".to_string(), "kanagawa_dragon".to_string()),
            ("tmux".to_string(), "kanagawa_dragon".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "kanagawa_dragon".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#dcd7ba".to_string(),
            background: "#0d0c0c".to_string(),
            cursor: Some("#d27e99".to_string()),
            selection_bg: Some("#2d4f45".to_string()),
            selection_fg: Some("#dcd7ba".to_string()),
            black: "#0d0c0c".to_string(),
            red: "#c34043".to_string(),
            green: "#7aa89f".to_string(),
            yellow: "#8a8c3b".to_string(),
            blue: "#658594".to_string(),
            magenta: "#9cabca".to_string(),
            cyan: "#7aa89f".to_string(),
            white: "#dcd7ba".to_string(),
            bright_black: "#464646".to_string(),
            bright_red: "#d97000".to_string(),
            bright_green: "#7aa89f".to_string(),
            bright_yellow: "#8a8c3b".to_string(),
            bright_blue: "#658594".to_string(),
            bright_magenta: "#9cabca".to_string(),
            bright_cyan: "#7aa89f".to_string(),
            bright_white: "#dcd7ba".to_string(),
            bg_dim: Some("#16161d".to_string()),
            bg_darker: Some("#0f0f14".to_string()),
            bg_darkest: Some("#0d0c0c".to_string()),
            rosewater: None,
            flamingo: None,
            pink: Some("#d27e99".to_string()),
            mauve: None,
            lavender: None,
            text: Some("#dcd7ba".to_string()),
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
            extras: HashMap::from([
                ("red".to_string(), "#c34043".to_string()),
                ("orange".to_string(), "#d97000".to_string()),
                ("yellow".to_string(), "#8a8c3b".to_string()),
                ("green".to_string(), "#7aa89f".to_string()),
                ("blue".to_string(), "#658594".to_string()),
                ("purple".to_string(), "#9cabca".to_string()),
                ("pink".to_string(), "#d27e99".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: None,
    })
}

/// Kanagawa Lotus — light, serene palette
/// https://github.com/rebelot/kanagawa.nvim
pub fn kanagawa_lotus() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "kanagawa-lotus".to_string(),
        name: "Kanagawa Lotus".to_string(),
        family: "Kanagawa".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Kanagawa Lotus".to_string()),
            ("alacritty".to_string(), "kanagawa_lotus".to_string()),
            ("bat".to_string(), "Kanagawa Lotus".to_string()),
            ("delta".to_string(), "kanagawa_lotus".to_string()),
            ("starship".to_string(), "kanagawa_lotus".to_string()),
            ("eza".to_string(), "kanagawa_lotus".to_string()),
            ("lazygit".to_string(), "kanagawa_lotus".to_string()),
            ("fastfetch".to_string(), "kanagawa_lotus".to_string()),
            ("tmux".to_string(), "kanagawa_lotus".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "kanagawa_lotus".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#1f1f28".to_string(),
            background: "#f2ecbc".to_string(),
            cursor: Some("#d27e99".to_string()),
            selection_bg: Some("#f0e68c".to_string()),
            selection_fg: Some("#1f1f28".to_string()),
            black: "#f2ecbc".to_string(),
            red: "#c34043".to_string(),
            green: "#7aa89f".to_string(),
            yellow: "#8a8c3b".to_string(),
            blue: "#658594".to_string(),
            magenta: "#9cabca".to_string(),
            cyan: "#7aa89f".to_string(),
            white: "#1f1f28".to_string(),
            bright_black: "#c0c0a0".to_string(),
            bright_red: "#d97000".to_string(),
            bright_green: "#7aa89f".to_string(),
            bright_yellow: "#8a8c3b".to_string(),
            bright_blue: "#658594".to_string(),
            bright_magenta: "#9cabca".to_string(),
            bright_cyan: "#7aa89f".to_string(),
            bright_white: "#1f1f28".to_string(),
            bg_dim: Some("#f5f0dc".to_string()),
            bg_darker: Some("#f0ecd4".to_string()),
            bg_darkest: Some("#f2ecbc".to_string()),
            rosewater: None,
            flamingo: None,
            pink: Some("#d27e99".to_string()),
            mauve: None,
            lavender: None,
            text: Some("#1f1f28".to_string()),
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
            extras: HashMap::from([
                ("red".to_string(), "#c34043".to_string()),
                ("orange".to_string(), "#d97000".to_string()),
                ("yellow".to_string(), "#8a8c3b".to_string()),
                ("green".to_string(), "#7aa89f".to_string()),
                ("blue".to_string(), "#658594".to_string()),
                ("purple".to_string(), "#9cabca".to_string()),
                ("pink".to_string(), "#d27e99".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Light,
        auto_pair: Some("kanagawa-wave"),
    })
}
