use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Nord — arctic, north-bluish color palette
pub fn nord() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "nord".to_string(),
        name: "Nord".to_string(),
        family: "Nord".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Nord".to_string()),
            ("alacritty".to_string(), "nord".to_string()),
            ("bat".to_string(), "Nord".to_string()),
            ("delta".to_string(), "nord".to_string()),
            ("starship".to_string(), "nord".to_string()),
            ("eza".to_string(), "nord".to_string()),
            ("lazygit".to_string(), "nord".to_string()),
            ("fastfetch".to_string(), "nord".to_string()),
            ("tmux".to_string(), "nord".to_string()),
            ("zsh_syntax_highlighting".to_string(), "nord".to_string()),
        ]),
        palette: Palette {
            foreground: "#d8dee9".to_string(),
            background: "#2e3440".to_string(),
            cursor: Some("#d8dee9".to_string()),
            selection_bg: Some("#434c5e".to_string()),
            selection_fg: Some("#d8dee9".to_string()),
            black: "#434c5e".to_string(),
            red: "#bf616a".to_string(),
            green: "#a3be8c".to_string(),
            yellow: "#ebcb8b".to_string(),
            blue: "#81a1c1".to_string(),
            magenta: "#b48ead".to_string(),
            cyan: "#88c0d0".to_string(),
            white: "#eceff4".to_string(),
            bright_black: "#4c566a".to_string(),
            bright_red: "#bf616a".to_string(),
            bright_green: "#a3be8c".to_string(),
            bright_yellow: "#ebcb8b".to_string(),
            bright_blue: "#81a1c1".to_string(),
            bright_magenta: "#b48ead".to_string(),
            bright_cyan: "#88c0d0".to_string(),
            bright_white: "#eceff4".to_string(),
            bg_dim: Some("#3b4252".to_string()),
            bg_darker: Some("#2e3440".to_string()),
            bg_darkest: Some("#2e3440".to_string()),
            rosewater: Some("#eceff4".to_string()),
            flamingo: Some("#bf616a".to_string()),
            pink: Some("#b48ead".to_string()),
            mauve: Some("#b48ead".to_string()),
            lavender: Some("#a3be8c".to_string()),
            text: Some("#eceff4".to_string()),
            subtext1: Some("#d8dee9".to_string()),
            subtext0: Some("#4c566a".to_string()),
            overlay2: Some("#4c566a".to_string()),
            overlay1: Some("#434c5e".to_string()),
            overlay0: Some("#3b4252".to_string()),
            surface2: Some("#434c5e".to_string()),
            surface1: Some("#3b4252".to_string()),
            surface0: Some("#2e3440".to_string()),
            extras: HashMap::new(),
        },
    })
}
