use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Rosé Pine Main — dark, cozy palette
/// https://rosepinetheme.com/
pub fn rose_pine_main() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "rose-pine-main".to_string(),
        name: "Rosé Pine Main".to_string(),
        family: "Rosé Pine".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Rosé Pine".to_string()),
            ("alacritty".to_string(), "rose_pine".to_string()),
            ("bat".to_string(), "Rosé Pine".to_string()),
            ("delta".to_string(), "rose_pine".to_string()),
            ("starship".to_string(), "rose_pine".to_string()),
            ("eza".to_string(), "rose_pine".to_string()),
            ("lazygit".to_string(), "rose_pine".to_string()),
            ("fastfetch".to_string(), "rose_pine".to_string()),
            ("tmux".to_string(), "rose_pine".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "rose_pine".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#e0def4".to_string(),
            background: "#191724".to_string(),
            cursor: Some("#eb6f92".to_string()),
            selection_bg: Some("#26233a".to_string()),
            selection_fg: Some("#e0def4".to_string()),
            black: "#191724".to_string(),
            red: "#eb6f92".to_string(),
            green: "#31748f".to_string(),
            yellow: "#f6c177".to_string(),
            blue: "#c4a7e7".to_string(),
            magenta: "#ea9a97".to_string(),
            cyan: "#9ccfd8".to_string(),
            white: "#e0def4".to_string(),
            bright_black: "#6e6a86".to_string(),
            bright_red: "#eb6f92".to_string(),
            bright_green: "#31748f".to_string(),
            bright_yellow: "#f6c177".to_string(),
            bright_blue: "#c4a7e7".to_string(),
            bright_magenta: "#ea9a97".to_string(),
            bright_cyan: "#9ccfd8".to_string(),
            bright_white: "#e0def4".to_string(),
            bg_dim: Some("#1f1d2e".to_string()),
            bg_darker: Some("#26233a".to_string()),
            bg_darkest: Some("#191724".to_string()),
            rosewater: None,
            flamingo: None,
            pink: None,
            mauve: None,
            lavender: None,
            text: Some("#e0def4".to_string()),
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
            extras: HashMap::from([
                ("love".to_string(), "#eb6f92".to_string()),
                ("gold".to_string(), "#f6c177".to_string()),
                ("rose".to_string(), "#ea9a97".to_string()),
                ("pine".to_string(), "#31748f".to_string()),
                ("foam".to_string(), "#9ccfd8".to_string()),
                ("iris".to_string(), "#c4a7e7".to_string()),
                ("muted".to_string(), "#6e6a86".to_string()),
                ("subtle".to_string(), "#908caa".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("rose-pine-dawn"),
    })
}

/// Rosé Pine Moon — dark, moodier palette
/// https://rosepinetheme.com/
pub fn rose_pine_moon() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "rose-pine-moon".to_string(),
        name: "Rosé Pine Moon".to_string(),
        family: "Rosé Pine".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Rosé Pine Moon".to_string()),
            ("alacritty".to_string(), "rose_pine_moon".to_string()),
            ("bat".to_string(), "Rosé Pine Moon".to_string()),
            ("delta".to_string(), "rose_pine_moon".to_string()),
            ("starship".to_string(), "rose_pine_moon".to_string()),
            ("eza".to_string(), "rose_pine_moon".to_string()),
            ("lazygit".to_string(), "rose_pine_moon".to_string()),
            ("fastfetch".to_string(), "rose_pine_moon".to_string()),
            ("tmux".to_string(), "rose_pine_moon".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "rose_pine_moon".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#e0def4".to_string(),
            background: "#232136".to_string(),
            cursor: Some("#eb6f92".to_string()),
            selection_bg: Some("#302e42".to_string()),
            selection_fg: Some("#e0def4".to_string()),
            black: "#232136".to_string(),
            red: "#eb6f92".to_string(),
            green: "#31748f".to_string(),
            yellow: "#f6c177".to_string(),
            blue: "#c4a7e7".to_string(),
            magenta: "#ea9a97".to_string(),
            cyan: "#9ccfd8".to_string(),
            white: "#e0def4".to_string(),
            bright_black: "#6e6a86".to_string(),
            bright_red: "#eb6f92".to_string(),
            bright_green: "#31748f".to_string(),
            bright_yellow: "#f6c177".to_string(),
            bright_blue: "#c4a7e7".to_string(),
            bright_magenta: "#ea9a97".to_string(),
            bright_cyan: "#9ccfd8".to_string(),
            bright_white: "#e0def4".to_string(),
            bg_dim: Some("#2a273f".to_string()),
            bg_darker: Some("#302e42".to_string()),
            bg_darkest: Some("#232136".to_string()),
            rosewater: None,
            flamingo: None,
            pink: None,
            mauve: None,
            lavender: None,
            text: Some("#e0def4".to_string()),
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
            extras: HashMap::from([
                ("love".to_string(), "#eb6f92".to_string()),
                ("gold".to_string(), "#f6c177".to_string()),
                ("rose".to_string(), "#ea9a97".to_string()),
                ("pine".to_string(), "#31748f".to_string()),
                ("foam".to_string(), "#9ccfd8".to_string()),
                ("iris".to_string(), "#c4a7e7".to_string()),
                ("muted".to_string(), "#6e6a86".to_string()),
                ("subtle".to_string(), "#908caa".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: None,
    })
}

/// Rosé Pine Dawn — light, warm palette
/// https://rosepinetheme.com/
pub fn rose_pine_dawn() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "rose-pine-dawn".to_string(),
        name: "Rosé Pine Dawn".to_string(),
        family: "Rosé Pine".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Rosé Pine Dawn".to_string()),
            ("alacritty".to_string(), "rose_pine_dawn".to_string()),
            ("bat".to_string(), "Rosé Pine Dawn".to_string()),
            ("delta".to_string(), "rose_pine_dawn".to_string()),
            ("starship".to_string(), "rose_pine_dawn".to_string()),
            ("eza".to_string(), "rose_pine_dawn".to_string()),
            ("lazygit".to_string(), "rose_pine_dawn".to_string()),
            ("fastfetch".to_string(), "rose_pine_dawn".to_string()),
            ("tmux".to_string(), "rose_pine_dawn".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "rose_pine_dawn".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#575279".to_string(),
            background: "#faf4ed".to_string(),
            cursor: Some("#b4637a".to_string()),
            selection_bg: Some("#f2e9de".to_string()),
            selection_fg: Some("#575279".to_string()),
            black: "#faf4ed".to_string(),
            red: "#b4637a".to_string(),
            green: "#286983".to_string(),
            yellow: "#ea9d34".to_string(),
            blue: "#907aa9".to_string(),
            magenta: "#d7828d".to_string(),
            cyan: "#56949f".to_string(),
            white: "#575279".to_string(),
            bright_black: "#9893a5".to_string(),
            bright_red: "#b4637a".to_string(),
            bright_green: "#286983".to_string(),
            bright_yellow: "#ea9d34".to_string(),
            bright_blue: "#907aa9".to_string(),
            bright_magenta: "#d7828d".to_string(),
            bright_cyan: "#56949f".to_string(),
            bright_white: "#575279".to_string(),
            bg_dim: Some("#f8f3f0".to_string()),
            bg_darker: Some("#f2e9de".to_string()),
            bg_darkest: Some("#faf4ed".to_string()),
            rosewater: None,
            flamingo: None,
            pink: None,
            mauve: None,
            lavender: None,
            text: Some("#575279".to_string()),
            subtext1: None,
            subtext0: None,
            overlay2: None,
            overlay1: None,
            overlay0: None,
            surface2: None,
            surface1: None,
            surface0: None,
            extras: HashMap::from([
                ("love".to_string(), "#b4637a".to_string()),
                ("gold".to_string(), "#ea9d34".to_string()),
                ("rose".to_string(), "#d7828d".to_string()),
                ("pine".to_string(), "#286983".to_string()),
                ("foam".to_string(), "#56949f".to_string()),
                ("iris".to_string(), "#907aa9".to_string()),
                ("muted".to_string(), "#9893a5".to_string()),
                ("subtle".to_string(), "#d7d1cc".to_string()),
            ]),
        },
        appearance: crate::theme::ThemeAppearance::Light,
        auto_pair: Some("rose-pine-main"),
    })
}
