use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Tokyo Night Light — light, modern palette
pub fn tokyo_night_light() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "tokyo-night-light".to_string(),
        name: "Tokyo Night Light".to_string(),
        family: "Tokyo Night".to_string(),
        tool_refs: HashMap::from([
            // Ghostty ships this family as "TokyoNight" (no space) with " Day"
            // suffix for the light variant. Verified via `ghostty +list-themes`
            // on Ghostty 1.3.1.
            ("ghostty".to_string(), "TokyoNight Day".to_string()),
            ("alacritty".to_string(), "tokyo_night_light".to_string()),
            ("bat".to_string(), "Tokyo Night Light".to_string()),
            ("delta".to_string(), "tokyo_night_light".to_string()),
            ("starship".to_string(), "tokyo_night_light".to_string()),
            ("eza".to_string(), "tokyo_night_light".to_string()),
            ("lazygit".to_string(), "tokyo_night_light".to_string()),
            ("fastfetch".to_string(), "tokyo_night_light".to_string()),
            ("tmux".to_string(), "tokyo_night_light".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "tokyo_night_light".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#3760bf".to_string(),
            background: "#e1e2e7".to_string(),
            cursor: Some("#3760bf".to_string()),
            selection_bg: Some("#99a7df".to_string()),
            selection_fg: Some("#3760bf".to_string()),
            black: "#e9e9ed".to_string(),
            red: "#f52a65".to_string(),
            green: "#587539".to_string(),
            yellow: "#8c6c3e".to_string(),
            blue: "#2e7de9".to_string(),
            magenta: "#9854f1".to_string(),
            cyan: "#007197".to_string(),
            white: "#6172b0".to_string(),
            bright_black: "#a1a6c5".to_string(),
            bright_red: "#f52a65".to_string(),
            bright_green: "#587539".to_string(),
            bright_yellow: "#8c6c3e".to_string(),
            bright_blue: "#2e7de9".to_string(),
            bright_magenta: "#9854f1".to_string(),
            bright_cyan: "#007197".to_string(),
            bright_white: "#3760bf".to_string(),
            bg_dim: Some("#f5f5f5".to_string()),
            bg_darker: Some("#eeeeee".to_string()),
            bg_darkest: Some("#e8e8e8".to_string()),
            rosewater: Some("#c0caf5".to_string()),
            flamingo: Some("#f7768e".to_string()),
            pink: Some("#f7768e".to_string()),
            mauve: Some("#9d7cd8".to_string()),
            lavender: Some("#7aa2f7".to_string()),
            text: Some("#c0caf5".to_string()),
            subtext1: Some("#a9b1d6".to_string()),
            subtext0: Some("#565f89".to_string()),
            overlay2: Some("#444b6a".to_string()),
            overlay1: Some("#3f4751".to_string()),
            overlay0: Some("#16161e".to_string()),
            surface2: Some("#444b6a".to_string()),
            surface1: Some("#3f4751".to_string()),
            surface0: Some("#1a1b26".to_string()),
            extras: HashMap::new(),
        },
        appearance: crate::theme::ThemeAppearance::Light,
        auto_pair: Some("tokyo-night-dark"),
    })
}

/// Tokyo Night Dark — dark, vibrant palette
pub fn tokyo_night_dark() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "tokyo-night-dark".to_string(),
        name: "Tokyo Night Dark".to_string(),
        family: "Tokyo Night".to_string(),
        tool_refs: HashMap::from([
            // Ghostty ships this family as "TokyoNight" (no space). The plain
            // "TokyoNight" entry is the dark variant. Verified via
            // `ghostty +list-themes` on Ghostty 1.3.1.
            ("ghostty".to_string(), "TokyoNight".to_string()),
            ("alacritty".to_string(), "tokyo_night_dark".to_string()),
            ("bat".to_string(), "Tokyo Night".to_string()),
            ("delta".to_string(), "tokyo_night_dark".to_string()),
            ("starship".to_string(), "tokyo_night_dark".to_string()),
            ("eza".to_string(), "tokyo_night_dark".to_string()),
            ("lazygit".to_string(), "tokyo_night_dark".to_string()),
            ("fastfetch".to_string(), "tokyo_night_dark".to_string()),
            ("tmux".to_string(), "tokyo_night_dark".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "tokyo_night_dark".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#c0caf5".to_string(),
            background: "#1a1b26".to_string(),
            cursor: Some("#c0caf5".to_string()),
            selection_bg: Some("#283457".to_string()),
            selection_fg: Some("#c0caf5".to_string()),
            black: "#15161e".to_string(),
            red: "#f7768e".to_string(),
            green: "#9ece6a".to_string(),
            yellow: "#e0af68".to_string(),
            blue: "#7aa2f7".to_string(),
            magenta: "#bb9af7".to_string(),
            cyan: "#7dcfff".to_string(),
            white: "#a9b1d6".to_string(),
            bright_black: "#414868".to_string(),
            bright_red: "#f7768e".to_string(),
            bright_green: "#9ece6a".to_string(),
            bright_yellow: "#e0af68".to_string(),
            bright_blue: "#7aa2f7".to_string(),
            bright_magenta: "#bb9af7".to_string(),
            bright_cyan: "#7dcfff".to_string(),
            bright_white: "#c0caf5".to_string(),
            bg_dim: Some("#2a2b35".to_string()),
            bg_darker: Some("#1f2029".to_string()),
            bg_darkest: Some("#16161e".to_string()),
            rosewater: Some("#c0caf5".to_string()),
            flamingo: Some("#f7768e".to_string()),
            pink: Some("#f7768e".to_string()),
            mauve: Some("#9d7cd8".to_string()),
            lavender: Some("#7aa2f7".to_string()),
            text: Some("#c0caf5".to_string()),
            subtext1: Some("#a9b1d6".to_string()),
            subtext0: Some("#565f89".to_string()),
            overlay2: Some("#444b6a".to_string()),
            overlay1: Some("#3f4751".to_string()),
            overlay0: Some("#16161e".to_string()),
            surface2: Some("#444b6a".to_string()),
            surface1: Some("#3f4751".to_string()),
            surface0: Some("#1a1b26".to_string()),
            extras: HashMap::new(),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("tokyo-night-light"),
    })
}
