use super::{Palette, ThemeVariant};
use crate::error::Result;
use std::collections::HashMap;

/// Tokyo Night Light — light, modern palette
pub fn tokyo_night_light() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "tokyo-night-light".to_string(),
        name: "Tokyo Night Light".to_string(),
        family: "Tokyo Night".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Tokyo Night Light".to_string()),
            ("alacritty".to_string(), "tokyo_night_light".to_string()),
            ("bat".to_string(), "Tokyo Night Light".to_string()),
            ("delta".to_string(), "tokyo_night_light".to_string()),
            ("starship".to_string(), "tokyo_night_light".to_string()),
            ("eza".to_string(), "tokyo_night_light".to_string()),
            ("lazygit".to_string(), "tokyo_night_light".to_string()),
            ("fastfetch".to_string(), "tokyo_night_light".to_string()),
            ("tmux".to_string(), "tokyo_night_light".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "tokyo_night_light".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#3760f6".to_string(),
            background: "#ffffff".to_string(),
            cursor: Some("#0184bc".to_string()),
            selection_bg: Some("#e0e0e0".to_string()),
            selection_fg: Some("#3760f6".to_string()),
            black: "#757575".to_string(),
            red: "#f52a65".to_string(),
            green: "#587539".to_string(),
            yellow: "#8f8f00".to_string(),
            blue: "#2e7de9".to_string(),
            magenta: "#b15ea4".to_string(),
            cyan: "#007197".to_string(),
            white: "#ffffff".to_string(),
            bright_black: "#9e9e9e".to_string(),
            bright_red: "#f52a65".to_string(),
            bright_green: "#587539".to_string(),
            bright_yellow: "#8f8f00".to_string(),
            bright_blue: "#2e7de9".to_string(),
            bright_magenta: "#b15ea4".to_string(),
            bright_cyan: "#007197".to_string(),
            bright_white: "#ffffff".to_string(),
            bg_dim: Some("#f5f5f5".to_string()),
            bg_darker: Some("#eeeeee".to_string()),
            bg_darkest: Some("#e8e8e8".to_string()),
            rosewater: Some("#c0caf5".to_string()),
            flamingo: Some("#f7768e".to_string()),
            pink: Some("#f7768e".to_string()),
            mauve: Some("#9d7cd8".to_string()),
            lavender: Some("#7aa2f7".to_string()),
            text: Some("#c0caf5".to_string()),
            subtext1: Some("#a9b1d6".to_string()),
            subtext0: Some("#565f89".to_string()),
            overlay2: Some("#444b6a".to_string()),
            overlay1: Some("#3f4751".to_string()),
            overlay0: Some("#16161e".to_string()),
            surface2: Some("#444b6a".to_string()),
            surface1: Some("#3f4751".to_string()),
            surface0: Some("#1a1b26".to_string()),
            extras: HashMap::new(),
        },
        appearance: crate::theme::ThemeAppearance::Light,
        auto_pair: Some("tokyo-night-dark"),
    })
}

/// Tokyo Night Dark — dark, vibrant palette
pub fn tokyo_night_dark() -> Result<ThemeVariant> {
    Ok(ThemeVariant {
        id: "tokyo-night-dark".to_string(),
        name: "Tokyo Night Dark".to_string(),
        family: "Tokyo Night".to_string(),
        tool_refs: HashMap::from([
            ("ghostty".to_string(), "Tokyo Night".to_string()), // Ghostty uses "Tokyo Night" not "Tokyo Night Dark"
            ("alacritty".to_string(), "tokyo_night_dark".to_string()),
            ("bat".to_string(), "Tokyo Night".to_string()),
            ("delta".to_string(), "tokyo_night_dark".to_string()),
            ("starship".to_string(), "tokyo_night_dark".to_string()),
            ("eza".to_string(), "tokyo_night_dark".to_string()),
            ("lazygit".to_string(), "tokyo_night_dark".to_string()),
            ("fastfetch".to_string(), "tokyo_night_dark".to_string()),
            ("tmux".to_string(), "tokyo_night_dark".to_string()),
            (
                "zsh_syntax_highlighting".to_string(),
                "tokyo_night_dark".to_string(),
            ),
        ]),
        palette: Palette {
            foreground: "#c0caf5".to_string(),
            background: "#1a1b26".to_string(),
            cursor: Some("#7aa2f7".to_string()),
            selection_bg: Some("#364a82".to_string()),
            selection_fg: Some("#c0caf5".to_string()),
            black: "#565f89".to_string(),
            red: "#f7768e".to_string(),
            green: "#9ece6a".to_string(),
            yellow: "#e0af68".to_string(),
            blue: "#7aa2f7".to_string(),
            magenta: "#bb9af7".to_string(),
            cyan: "#7dcfff".to_string(),
            white: "#ffffff".to_string(),
            bright_black: "#7aa1f0".to_string(),
            bright_red: "#f7768e".to_string(),
            bright_green: "#9ece6a".to_string(),
            bright_yellow: "#e0af68".to_string(),
            bright_blue: "#7aa2f7".to_string(),
            bright_magenta: "#bb9af7".to_string(),
            bright_cyan: "#7dcfff".to_string(),
            bright_white: "#ffffff".to_string(),
            bg_dim: Some("#2a2b35".to_string()),
            bg_darker: Some("#1f2029".to_string()),
            bg_darkest: Some("#16161e".to_string()),
            rosewater: Some("#c0caf5".to_string()),
            flamingo: Some("#f7768e".to_string()),
            pink: Some("#f7768e".to_string()),
            mauve: Some("#9d7cd8".to_string()),
            lavender: Some("#7aa2f7".to_string()),
            text: Some("#c0caf5".to_string()),
            subtext1: Some("#a9b1d6".to_string()),
            subtext0: Some("#565f89".to_string()),
            overlay2: Some("#444b6a".to_string()),
            overlay1: Some("#3f4751".to_string()),
            overlay0: Some("#16161e".to_string()),
            surface2: Some("#444b6a".to_string()),
            surface1: Some("#3f4751".to_string()),
            surface0: Some("#1a1b26".to_string()),
            extras: HashMap::new(),
        },
        appearance: crate::theme::ThemeAppearance::Dark,
        auto_pair: Some("tokyo-night-light"),
    })
}
