use std::path::{Path, PathBuf};
use std::fs;
use std::io::Write;
use atomic_write_file::AtomicWriteFile;
use toml_edit::DocumentMut;
use crate::error::Result;

/// Three-tier configuration manager.
/// Manages three tiers per /// 1. Managed tier: ~/.config/slate/managed/{tool}/ — Slate writes here (regenerates freely)
/// 2. Integration tier: ~/.config/{tool}/config — User's entry file (slate ensures it includes managed, never modifies content)
/// 3. User tier: ~/.config/slate/user/{tool}/ — User's custom overrides (slate never touches)
pub struct ConfigManager {
    base_path: PathBuf,  // ~/.config/slate
}

impl ConfigManager {
    /// Create ConfigManager with default base path.
    /// hardcode ~/.config/slate/ (macOS-only, no ProjectDirs)
    pub fn new() -> Result<Self> {
        let home = std::env::var("HOME")
            .map_err(|_| crate::error::SlateError::MissingHomeDir)?;

        let base_path = PathBuf::from(home).join(".config/slate");

        // Ensure base directory exists
        fs::create_dir_all(&base_path)?;

        Ok(Self { base_path })
    }

    /// Path to managed directory for a tool
    /// Example: ~/.config/slate/managed/ghostty
    fn managed_dir(&self, tool: &str) -> PathBuf {
        self.base_path.join("managed").join(tool)
    }

    /// Path to user override directory for a tool
    /// Example: ~/.config/slate/user/ghostty
    fn user_dir(&self, tool: &str) -> PathBuf {
        self.base_path.join("user").join(tool)
    }

    /// Path to shell environment integration file
    /// ~/.config/slate/env.sh — sourced by user's .zshrc 
    fn shell_env_path(&self) -> PathBuf {
        self.base_path.join("env.sh")
    }

    /// Path to current theme tracking file
    /// ~/.config/slate/current — plain text file with theme ID 
    fn current_theme_path(&self) -> PathBuf {
        self.base_path.join("current")
    }

    /// Write managed config for a tool.
    /// Slate owns this tier — regenerate freely without losing user data.
    /// Use atomic_write_file to prevent partial writes.
    /// Per RESEARCH: Use canonicalize() to prevent symlink attacks.
    pub fn write_managed_file(&self, tool: &str, filename: &str, content: &str) -> Result<()> {
        let dir = self.managed_dir(tool);
        fs::create_dir_all(&dir)?;

        let path = dir.join(filename);

        // Resolve symlinks to prevent substitution attacks
        let _canonical_parent = dir.canonicalize()?;

        // Atomic write to prevent TOCTOU and partial writes
        let mut file = AtomicWriteFile::open(&path)?;
        file.write_all(content.as_bytes())?;
        file.commit()?;

        Ok(())
    }

    /// Update shell environment file (~/.config/slate/env.sh).
    /// generated by slate, user sources once in .zshrc.
    /// Contains all env var exports + source commands.
    /// This is called whenever theme switches to update env vars atomically.
    pub fn update_shell_env(&self, env_content: &str) -> Result<()> {
        let path = self.shell_env_path();

        // Atomic write
        let mut file = AtomicWriteFile::open(&path)?;
        file.write_all(env_content.as_bytes())?;
        file.commit()?;

        // Ensure file is executable (readable by shell)
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = fs::Permissions::from_mode(0o644);  // rw-r--r--
            fs::set_permissions(&path, perms)?;
        }

        Ok(())
    }

    /// Update current theme tracking file.
    /// plain text file with theme ID.
    pub fn set_current_theme(&self, theme_id: &str) -> Result<()> {
        let path = self.current_theme_path();
        let mut file = AtomicWriteFile::open(&path)?;
        file.write_all(theme_id.as_bytes())?;
        file.commit()?;
        Ok(())
    }

    /// Get current theme ID from tracking file.
    pub fn get_current_theme(&self) -> Result<Option<String>> {
        let path = self.current_theme_path();

        if !path.exists() {
            return Ok(None);
        }

        let content = fs::read_to_string(&path)?;
        Ok(Some(content.trim().to_string()))
    }

    /// Edit a field in a TOML config file using AST-aware editing.
    /// Per RESEARCH Pitfall 1: Use toml_edit, never regex.
    /// Preserves comments and formatting.
    /// Note: This implementation supports single-level keys only.
    /// For nested keys, adapters should implement their own TOML editing logic.
    /// Example:
    /// ```ignore
    /// config.edit_config_field(
    /// Path::new("~/.config/starship.toml"),
    /// &["palette"],
    /// "catppuccin_mocha"
    /// )?;
    /// ```
    pub fn edit_config_field(
        &self,
        config_path: &Path,
        keys: &[&str],
        value: &str,
    ) -> Result<()> {
        if !config_path.exists() {
            return Err(crate::error::SlateError::ConfigNotFound(
                config_path.to_string_lossy().to_string()
            ));
        }

        // Read existing TOML
        let content = fs::read_to_string(config_path)?;
        let mut doc: DocumentMut = content.parse()?;

        // For now, support only top-level keys (single element in keys array)
        // adapters can implement their own more complex TOML editing
        if keys.len() == 1 {
            doc[keys[0]] = toml_edit::value(value);
        } else {
            // For multi-level keys, we'd need recursive navigation which is complex with DocumentMut
            // Adapters should implement custom logic instead
            return Err(crate::error::SlateError::Internal(
                "Multi-level TOML editing not yet supported; use adapter-specific logic".to_string()
            ));
        }

        // Write back with atomic write
        let mut file = AtomicWriteFile::open(config_path)?;
        file.write_all(doc.to_string().as_bytes())?;
        file.commit()?;

        Ok(())
    }

    /// Ensure integration file includes managed config via include directive.
    /// This is called by adapters to set up the include relationship.
    /// For TOML files: adds `include = "path"` line
    /// For shell scripts: adds `source /path/to/file` line
    /// For git config: adds `[include] path = ...` section
    /// Idempotent: if include already present, does nothing.
    pub fn ensure_integration_includes_managed(
        &self,
        config_path: &Path,
        _managed_path: &Path,
    ) -> Result<()> {
        if !config_path.exists() {
            // Integration file doesn't exist yet; may be created by tool on first run
            // This is not an error — tool will create it
            return Ok(());
        }

        // For now, this is a placeholder for adapters to implement per-tool logic
        // Each adapter will have its own way of ensuring the include is present
        // (some use TOML include syntax, some use environment variables, some use source commands)

        Ok(())
    }

    /// Get the base path for three-tier config
    pub fn base_path(&self) -> &Path {
        &self.base_path
    }
}

impl Default for ConfigManager {
    fn default() -> Self {
        // In production, this could fail if $HOME is not set
        // Tests should handle this via environment setup
        Self::new().expect("Failed to initialize ConfigManager")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_config_manager_creates_base_path() {
        // Test that ConfigManager can be created
        // Using real environment HOME for integration test
        match ConfigManager::new() {
            Ok(cm) => {
                // Verify base_path exists and is correct
                assert!(cm.base_path.ends_with(".config/slate"));
            }
            Err(_) => {
                // HOME not set in test env, that's ok
            }
        }
    }

    #[test]
    fn test_managed_file_write() {
        let temp = TempDir::new().unwrap();
        let config_manager = ConfigManager {
            base_path: temp.path().to_path_buf(),
        };

        let result = config_manager.write_managed_file(
            "ghostty",
            "colors.conf",
            "# Managed config\ncolor0 = #000000"
        );

        assert!(result.is_ok());

        let managed_file = config_manager.managed_dir("ghostty").join("colors.conf");
        assert!(managed_file.exists());

        let content = fs::read_to_string(&managed_file).unwrap();
        assert!(content.contains("color0"));
    }

    #[test]
    fn test_current_theme_tracking() {
        let temp = TempDir::new().unwrap();
        let config_manager = ConfigManager {
            base_path: temp.path().to_path_buf(),
        };

        // Initially no theme set
        let current = config_manager.get_current_theme().unwrap();
        assert_eq!(current, None);

        // Set theme
        config_manager.set_current_theme("catppuccin_mocha").unwrap();

        // Verify it was set
        let current = config_manager.get_current_theme().unwrap();
        assert_eq!(current, Some("catppuccin_mocha".to_string()));
    }

    #[test]
    fn test_shell_env_write() {
        let temp = TempDir::new().unwrap();
        let config_manager = ConfigManager {
            base_path: temp.path().to_path_buf(),
        };

        let env_content = "export BAT_THEME=catppuccin_mocha\nexport EZA_CONFIG_DIR=~/.config/slate/managed/eza";
        let result = config_manager.update_shell_env(env_content);

        assert!(result.is_ok());

        let env_file = config_manager.shell_env_path();
        assert!(env_file.exists());

        let content = fs::read_to_string(&env_file).unwrap();
        assert!(content.contains("BAT_THEME"));
    }

    #[test]
    fn test_edit_config_field_single_level() {
        let temp = TempDir::new().unwrap();
        let config_path = temp.path().join("config.toml");
        
        // Create a test config file
        let initial = r#"
palette = "old"
format = "..."
"#;
        fs::write(&config_path, initial).unwrap();

        let config_manager = ConfigManager {
            base_path: temp.path().to_path_buf(),
        };

        // Edit the palette key
        let result = config_manager.edit_config_field(
            &config_path,
            &["palette"],
            "new-palette"
        );

        assert!(result.is_ok());

        let content = fs::read_to_string(&config_path).unwrap();
        assert!(content.contains("new-palette"));
        assert!(!content.contains("\"old\""));
    }
}
