//! Prepared shell-preference files. Persist intent last; file publication is not
//! a transaction with external editors or native watcher processes.
use super::{
    file_read::{self, Links, Source, MAX_DOCUMENT_BYTES, MAX_STATE_BYTES, MAX_TOOL_CONFIG_BYTES},
    recovery_paths,
    state_files::atomic_write_synced_mode,
    ConfigManager,
};
use crate::{
    env::SlateEnv,
    error::{Result, SlateError},
};
use std::path::{Path, PathBuf};

#[derive(Clone, Copy)]
pub(crate) enum ShellPreference {
    Fastfetch(bool),
    AutoTheme(bool),
    Starship(bool),
    Highlighting(bool),
}

fn failure(path: &Path, reason: impl std::fmt::Display) -> SlateError {
    SlateError::ConfigWriteError(
        format!("{path:?}"),
        format!("Shell preference: {reason}; file contents omitted"),
    )
}

struct File {
    path: PathBuf,
    location: PathBuf,
    original: Option<Source>,
    desired: Option<Vec<u8>>,
    limit: u64,
}

impl File {
    fn capture(env: &SlateEnv, path: PathBuf, limit: u64) -> Result<Self> {
        Self::capture_with(env, path, limit, |path| {
            file_read::read(path, limit, Links::Reject).map_err(|error| failure(path, error))
        })
    }

    fn capture_with(
        env: &SlateEnv,
        path: PathBuf,
        limit: u64,
        read: impl FnOnce(&Path) -> Result<Option<Source>>,
    ) -> Result<Self> {
        recovery_paths::validate_file_path(env, &path, "shell preference")?;
        let location = file_read::directory_alias_target(&path)
            .ok_or_else(|| failure(&path, "cannot resolve parent path"))?;
        let original = read(&path)?;
        if file_read::directory_alias_target(&path).as_ref() != Some(&location) {
            return Err(failure(
                &path,
                "parent path changed while reading; prepare again",
            ));
        }
        Ok(Self {
            path,
            location,
            original,
            desired: None,
            limit,
        })
    }
    fn set(&mut self, desired: Option<Vec<u8>>) -> Result<()> {
        if desired
            .as_ref()
            .is_some_and(|bytes| bytes.len() as u64 > self.limit)
        {
            return Err(failure(&self.path, "generated bytes exceed the file limit"));
        }
        self.desired = desired;
        Ok(())
    }
    fn changed(&self) -> bool {
        self.original.as_ref().map(|source| source.bytes.as_slice()) != self.desired.as_deref()
    }
    fn verify(&self, env: &SlateEnv) -> Result<()> {
        let current = Self::capture(env, self.path.clone(), self.limit)?;
        if current.original != self.original || current.location != self.location {
            return Err(failure(
                &self.path,
                "file or parent path changed after preparation; retry without overwriting later edits",
            ));
        }
        Ok(())
    }
    fn publish(&self, env: &SlateEnv) -> Result<()> {
        self.verify(env)?;
        if !self.changed() {
            return Ok(());
        }
        match &self.desired {
            Some(bytes) => {
                std::fs::create_dir_all(
                    self.path
                        .parent()
                        .ok_or_else(|| failure(&self.path, "missing parent"))?,
                )?;
                self.verify(env)?;
                atomic_write_synced_mode(
                    &self.path,
                    bytes,
                    self.original
                        .as_ref()
                        .and_then(|source| source.mode)
                        .or(Some(0o600)),
                )
            }
            None => std::fs::remove_file(&self.path).map_err(Into::into),
        }
    }
}

pub(crate) struct PreparedShellPreference {
    env: SlateEnv,
    inputs: Vec<File>,
    files: Vec<File>,
}

impl PreparedShellPreference {
    pub(crate) fn capture(env: &SlateEnv, preference: ShellPreference) -> Result<Self> {
        let inputs = [
            ("current", MAX_STATE_BYTES),
            ("current-font", MAX_STATE_BYTES),
            ("config.toml", MAX_DOCUMENT_BYTES),
            ("autorun-fastfetch", MAX_STATE_BYTES),
        ]
        .into_iter()
        .map(|(name, limit)| File::capture(env, env.managed_file(name), limit))
        .collect::<Result<Vec<_>>>()?;
        let (fastfetch, auto_theme, path, limit) = match preference {
            ShellPreference::Fastfetch(enabled) => (
                Some(enabled),
                None,
                env.managed_file("autorun-fastfetch"),
                MAX_STATE_BYTES,
            ),
            ShellPreference::AutoTheme(enabled) => (
                None,
                Some(enabled),
                env.managed_file("config.toml"),
                MAX_DOCUMENT_BYTES,
            ),
            ShellPreference::Starship(_) | ShellPreference::Highlighting(_) => (
                None,
                None,
                env.managed_file("config.toml"),
                MAX_DOCUMENT_BYTES,
            ),
        };
        let mut intent = File::capture(env, path, limit)?;
        intent.set(match preference {
            ShellPreference::Fastfetch(enabled) => enabled.then(Vec::new),
            ShellPreference::AutoTheme(enabled) => Some(super::flags::flag_bytes(
                &intent.path,
                intent
                    .original
                    .as_ref()
                    .map(|source| source.bytes.as_slice()),
                "auto_theme",
                "enabled",
                enabled,
            )?),
            ShellPreference::Starship(enabled) | ShellPreference::Highlighting(enabled) => {
                Some(super::flags::flag_bytes(
                    &intent.path,
                    intent
                        .original
                        .as_ref()
                        .map(|source| source.bytes.as_slice()),
                    "tools",
                    if matches!(preference, ShellPreference::Starship(_)) {
                        "starship"
                    } else {
                        "zsh_highlighting"
                    },
                    enabled,
                )?)
            }
        })?;
        let config = ConfigManager::from_env_paths(env);
        let mut files = Vec::new();
        let starship = if let ShellPreference::Starship(enabled) = preference {
            Some(enabled)
        } else {
            None
        };
        let highlighting = if let ShellPreference::Highlighting(enabled) = preference {
            Some(enabled)
        } else {
            None
        };
        for (tool, name, content) in
            config.preference_shell_files(fastfetch, auto_theme, starship, highlighting)?
        {
            let mut file = File::capture(
                env,
                env.managed_file(&format!("managed/{tool}/{name}")),
                MAX_TOOL_CONFIG_BYTES,
            )?;
            file.set(Some(content.into_bytes()))?;
            files.push(file);
        }
        files.push(intent);
        let plan = Self {
            env: env.clone(),
            inputs,
            files,
        };
        plan.verify()?;
        Ok(plan)
    }
    pub(crate) fn paths(&self) -> Vec<PathBuf> {
        self.files.iter().map(|file| file.path.clone()).collect()
    }
    pub(crate) fn changed(&self) -> bool {
        self.files.iter().any(File::changed)
    }
    pub(crate) fn verify(&self) -> Result<()> {
        for file in self.inputs.iter().chain(&self.files) {
            file.verify(&self.env)?;
        }
        Ok(())
    }
    pub(crate) fn publish(&self) -> Result<()> {
        self.publish_with(|_| Ok(()))
    }
    fn publish_with(&self, mut before_file: impl FnMut(usize) -> Result<()>) -> Result<()> {
        self.verify()?;
        for (index, file) in self.files.iter().enumerate() {
            before_file(index)?;
            for input in &self.inputs {
                input.verify(&self.env)?;
            }
            file.publish(&self.env)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests;
