use crate::parser::ThemeJson;
use std::collections::HashMap;

/// Transform ThemeJson into Rust theme module source code.
/// Implements WCAG 2.1 contrast ratio algorithm for accessibility verification.
/// Reference: https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html
pub fn codegen_theme(theme: &ThemeJson) -> anyhow::Result<String> {
    let rust_id = to_rust_ident(&theme.id);
    let foreground = &theme.colors.foreground;
    let background = &theme.colors.background;

    // Check WCAG contrast for foreground vs background
    check_wcag_contrast(foreground, background, &theme.id, 4.5)?;

    // Build theme variant code
    let mut code = String::new();

    // Add file header
    code.push_str(&format!(
        "// @generated DO NOT EDIT\n\
         // This file is automatically generated by cargo xtask regen-themes\n\
         // Source: themes/{}.json (family: {})\n\
         \n",
        theme.id, theme.family
    ));

    // Generate Palette struct initialization
    code.push_str(&format!(
        "use crate::theme::Palette;\n\n\
         pub fn {}() -> Palette {{\n\
             Palette {{\n",
        rust_id
    ));

    // Add semantic colors
    code.push_str(&format!("        foreground: \"{}\".to_string(),\n", foreground));
    code.push_str(&format!("        background: \"{}\".to_string(),\n", background));
    code.push_str("        cursor: None,\n");
    code.push_str("        selection_bg: None,\n");
    code.push_str("        selection_fg: None,\n");

    // Add ANSI colors (check and adjust for danger zones)
    let (adjusted_colors, adjustments) = adjust_danger_zones(&theme)?;
    code.push_str(&format!("        black: \"{}\".to_string(),\n", adjusted_colors["black"]));
    code.push_str(&format!("        red: \"{}\".to_string(),\n", adjusted_colors["red"]));
    code.push_str(&format!("        green: \"{}\".to_string(),\n", adjusted_colors["green"]));

    // Annotate adjusted colors
    if let Some(original) = adjustments.get("yellow") {
        code.push_str(&format!(
            "        yellow: \"{}\".to_string(), // slate-adjusted: original {}, boosted for WCAG 4.5\n",
            adjusted_colors["yellow"], original
        ));
    } else {
        code.push_str(&format!("        yellow: \"{}\".to_string(),\n", adjusted_colors["yellow"]));
    }

    code.push_str(&format!("        blue: \"{}\".to_string(),\n", adjusted_colors["blue"]));
    code.push_str(&format!("        magenta: \"{}\".to_string(),\n", adjusted_colors["magenta"]));
    code.push_str(&format!("        cyan: \"{}\".to_string(),\n", adjusted_colors["cyan"]));
    code.push_str(&format!("        white: \"{}\".to_string(),\n", adjusted_colors["white"]));

    // Bright colors
    if let Some(original) = adjustments.get("bright_black") {
        code.push_str(&format!(
            "        bright_black: \"{}\".to_string(), // slate-adjusted: original {}\n",
            adjusted_colors["bright_black"], original
        ));
    } else {
        code.push_str(&format!(
            "        bright_black: \"{}\".to_string(),\n",
            adjusted_colors["bright_black"]
        ));
    }

    code.push_str(&format!(
        "        bright_red: \"{}\".to_string(),\n",
        adjusted_colors["bright_red"]
    ));
    code.push_str(&format!(
        "        bright_green: \"{}\".to_string(),\n",
        adjusted_colors["bright_green"]
    ));
    code.push_str(&format!(
        "        bright_yellow: \"{}\".to_string(),\n",
        adjusted_colors["bright_yellow"]
    ));
    code.push_str(&format!(
        "        bright_blue: \"{}\".to_string(),\n",
        adjusted_colors["bright_blue"]
    ));
    code.push_str(&format!(
        "        bright_magenta: \"{}\".to_string(),\n",
        adjusted_colors["bright_magenta"]
    ));
    code.push_str(&format!(
        "        bright_cyan: \"{}\".to_string(),\n",
        adjusted_colors["bright_cyan"]
    ));
    code.push_str(&format!(
        "        bright_white: \"{}\".to_string(),\n",
        adjusted_colors["bright_white"]
    ));

    // Add semantic backgrounds
    code.push_str(&format!("        bg_dim: Some(\"{}\".to_string()),\n", theme.semantic.bg_dim));
    code.push_str(&format!(
        "        bg_darker: Some(\"{}\".to_string()),\n",
        theme.semantic.bg_darker
    ));
    code.push_str(&format!(
        "        bg_darkest: Some(\"{}\".to_string()),\n",
        theme.semantic.bg_darkest
    ));

    // Add optional Catppuccin extras
    for (key, _value) in &[
        ("rosewater", "rosewater"),
        ("flamingo", "flamingo"),
        ("pink", "pink"),
        ("mauve", "mauve"),
        ("lavender", "lavender"),
        ("text", "text"),
        ("subtext1", "subtext1"),
        ("subtext0", "subtext0"),
        ("overlay2", "overlay2"),
        ("overlay1", "overlay1"),
        ("overlay0", "overlay0"),
        ("surface2", "surface2"),
        ("surface1", "surface1"),
        ("surface0", "surface0"),
    ] {
        code.push_str(&format!("        {}: None,\n", key));
    }

    // Add generic extras
    code.push_str("        extras: Default::default(),\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    Ok(code)
}

/// Convert snake_case theme id to rust function identifier.
/// Example: "catppuccin_mocha" -> "catppuccin_mocha"
fn to_rust_ident(theme_id: &str) -> String {
    theme_id.to_lowercase().replace("-", "_")
}

/// Check WCAG 2.1 contrast ratio (https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)
/// Fails if contrast is below minimum. Warnings are emitted but non-blocking.
fn check_wcag_contrast(fg: &str, bg: &str, theme_id: &str, minimum: f64) -> anyhow::Result<()> {
    let fg_rgb = hex_to_rgb(fg)?;
    let bg_rgb = hex_to_rgb(bg)?;

    let fg_lum = relative_luminance(fg_rgb.0, fg_rgb.1, fg_rgb.2);
    let bg_lum = relative_luminance(bg_rgb.0, bg_rgb.1, bg_rgb.2);

    let ratio = contrast_ratio(fg_lum, bg_lum);

    if ratio < minimum {
        eprintln!(
            "⚠ Warning: {} has low contrast ratio {:.2} (minimum {:.2})",
            theme_id, ratio, minimum
        );
    }

    Ok(())
}

/// Adjust colors in danger zones:
/// - Dark themes: adjust ANSI 4 (blue) and ANSI 8 (bright_black)
/// - Light themes: adjust ANSI 3 (yellow) and ANSI 8 (bright_black)
fn adjust_danger_zones(
    theme: &ThemeJson,
) -> anyhow::Result<(HashMap<String, String>, HashMap<String, String>)> {
    let mut adjusted = HashMap::new();
    let original_values = HashMap::new();

    // Copy all colors as-is for now (no adjustment in v1)
    adjusted.insert("foreground".to_string(), theme.colors.foreground.clone());
    adjusted.insert("background".to_string(), theme.colors.background.clone());
    adjusted.insert("black".to_string(), theme.colors.black.clone());
    adjusted.insert("red".to_string(), theme.colors.red.clone());
    adjusted.insert("green".to_string(), theme.colors.green.clone());
    adjusted.insert("yellow".to_string(), theme.colors.yellow.clone());
    adjusted.insert("blue".to_string(), theme.colors.blue.clone());
    adjusted.insert("magenta".to_string(), theme.colors.magenta.clone());
    adjusted.insert("cyan".to_string(), theme.colors.cyan.clone());
    adjusted.insert("white".to_string(), theme.colors.white.clone());
    adjusted.insert("bright_black".to_string(), theme.colors.bright_black.clone());
    adjusted.insert("bright_red".to_string(), theme.colors.bright_red.clone());
    adjusted.insert("bright_green".to_string(), theme.colors.bright_green.clone());
    adjusted.insert("bright_yellow".to_string(), theme.colors.bright_yellow.clone());
    adjusted.insert("bright_blue".to_string(), theme.colors.bright_blue.clone());
    adjusted.insert("bright_magenta".to_string(), theme.colors.bright_magenta.clone());
    adjusted.insert("bright_cyan".to_string(), theme.colors.bright_cyan.clone());
    adjusted.insert("bright_white".to_string(), theme.colors.bright_white.clone());

    Ok((adjusted, original_values))
}

/// Convert hex color #RRGGBB to (R, G, B) tuple.
fn hex_to_rgb(hex: &str) -> anyhow::Result<(u8, u8, u8)> {
    if !hex.starts_with('#') || hex.len() != 7 {
        return Err(anyhow::anyhow!("Invalid hex color: {}", hex));
    }

    let r = u8::from_str_radix(&hex[1..3], 16)?;
    let g = u8::from_str_radix(&hex[3..5], 16)?;
    let b = u8::from_str_radix(&hex[5..7], 16)?;

    Ok((r, g, b))
}

/// Calculate relative luminance per WCAG 2.1 formula.
/// Reference: https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html
fn relative_luminance(r: u8, g: u8, b: u8) -> f64 {
    let r = (r as f64) / 255.0;
    let g = (g as f64) / 255.0;
    let b = (b as f64) / 255.0;

    let r = if r <= 0.03928 {
        r / 12.92
    } else {
        ((r + 0.055) / 1.055).powf(2.4)
    };

    let g = if g <= 0.03928 {
        g / 12.92
    } else {
        ((g + 0.055) / 1.055).powf(2.4)
    };

    let b = if b <= 0.03928 {
        b / 12.92
    } else {
        ((b + 0.055) / 1.055).powf(2.4)
    };

    0.2126 * r + 0.7152 * g + 0.0722 * b
}

/// Calculate contrast ratio between two luminances.
fn contrast_ratio(l1: f64, l2: f64) -> f64 {
    let lighter = l1.max(l2);
    let darker = l1.min(l2);
    (lighter + 0.05) / (darker + 0.05)
}
