use std::fs;
use std::path::Path;
use std::process::Command;

/// Write generated Rust code to file with @generated header.
/// Uses atomic write to prevent partial files on error.
/// Reference: https://docs.rs/atomic-write-file/latest/
pub fn write_generated_file(path: &Path, content: &str) -> anyhow::Result<()> {
    // Write to temp file first
    let temp_path = path.with_extension("rs.tmp");

    fs::write(&temp_path, content)?;

    // Format with rustfmt
    Command::new("rustfmt")
        .arg(&temp_path)
        .output()
        .ok(); // Ignore rustfmt errors for now

    // Atomic move to final location
    fs::rename(&temp_path, path)?;

    eprintln!("  Wrote: {}", path.display());
    Ok(())
}

/// Generate mod.rs file that re-exports all theme modules.
pub fn generate_mod_rs(output_dir: &Path) -> anyhow::Result<()> {
    let mod_path = output_dir.join("mod.rs");

    // Collect all generated .rs files (except mod.rs itself)
    let mut modules = Vec::new();
    for entry in fs::read_dir(output_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.extension().map_or(false, |ext| ext == "rs") {
            if let Some(stem) = path.file_stem() {
                let name = stem.to_string_lossy().to_string();
                if name != "mod" {
                    modules.push(name);
                }
            }
        }
    }

    modules.sort();

    // Generate mod.rs content
    let mut content = String::from(
        "// @generated DO NOT EDIT\n\
         // This file is automatically generated by cargo xtask regen-themes\n\
         // It re-exports all generated theme modules.\n\n",
    );

    for module in &modules {
        content.push_str(&format!("mod {};\n", module));
    }

    content.push_str("\n// Re-export theme functions\n");
    for module in &modules {
        content.push_str(&format!("pub use {}::*;\n", module));
    }

    fs::write(&mod_path, &content)?;
    eprintln!("  Wrote: {}", mod_path.display());

    Ok(())
}
