//! Slate's own semantic mapping for the Yazi 26.9.1 flavor schema.
//! User theme.toml overrides still win over these defaults.
use crate::{error::Result, theme::ThemeVariant};
use std::fmt::Write;
type StyleGroup<'a> = (&'a str, Vec<(&'a str, &'a str, &'a str)>);

pub(super) const HEADER: &str = "# Generated by Slate: Yazi flavor (slate-sync)\n";
pub(super) const XML_HEADER: &str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated by Slate: Yazi syntax (slate-sync) -->\n";

pub(super) fn render(theme: &ThemeVariant) -> Result<(String, String)> {
    theme.validate()?;
    let p = &theme.palette;
    let background = p.background.as_str();
    let foreground = p.foreground.as_str();
    let surface = p
        .surface0
        .as_deref()
        .or(p.bg_dim.as_deref())
        .unwrap_or(background);
    let muted = p.bright_black.as_str();
    let selected = p.selection_bg.as_deref().unwrap_or(&p.blue);
    let contrast = |bg: &str| {
        crate::wcag::pick_accessible_fg_for_bg(&[foreground, background, &p.black, &p.white], bg)
    };
    let mut out = format!("{HEADER}\n[app]\noverall = {{ bg = {background:?} }}\n");
    let groups: [StyleGroup<'_>; 11] = [
        (
            "mgr",
            vec![
                ("cwd", &p.cyan, ""),
                ("find_keyword", &p.yellow, ""),
                ("find_position", &p.magenta, ""),
                ("symlink_target", &p.cyan, ""),
                ("marker_copied", &p.green, &p.green),
                ("marker_cut", &p.red, &p.red),
                ("marker_marked", &p.cyan, &p.cyan),
                ("marker_selected", &p.yellow, &p.yellow),
                ("border_style", muted, ""),
            ],
        ),
        (
            "status",
            vec![
                ("overall", foreground, surface),
                ("perm_type", &p.magenta, ""),
                ("perm_read", &p.green, ""),
                ("perm_write", &p.yellow, ""),
                ("perm_exec", &p.red, ""),
                ("perm_sep", muted, ""),
                ("progress_label", foreground, ""),
                ("progress_normal", &p.green, surface),
                ("progress_error", &p.red, surface),
            ],
        ),
        (
            "which",
            vec![
                ("border", &p.blue, ""),
                ("mask", foreground, background),
                ("cand", &p.cyan, ""),
                ("rest", muted, ""),
                ("desc", foreground, ""),
                ("separator_style", muted, ""),
            ],
        ),
        (
            "notify",
            vec![
                ("title_info", &p.green, ""),
                ("title_warn", &p.yellow, ""),
                ("title_error", &p.red, ""),
            ],
        ),
        (
            "confirm",
            vec![
                ("border", &p.blue, ""),
                ("title", &p.blue, ""),
                ("body", foreground, ""),
                ("list", foreground, ""),
            ],
        ),
        (
            "spot",
            vec![
                ("border", &p.blue, ""),
                ("title", &p.blue, ""),
                ("tbl_col", &p.cyan, ""),
            ],
        ),
        (
            "pick",
            vec![("border", &p.blue, ""), ("inactive", foreground, "")],
        ),
        (
            "input",
            vec![
                ("border", &p.blue, ""),
                ("title", &p.blue, ""),
                ("value", foreground, ""),
            ],
        ),
        (
            "cmp",
            vec![("border", &p.blue, ""), ("inactive", foreground, "")],
        ),
        (
            "tasks",
            vec![("border", &p.blue, ""), ("title", &p.blue, "")],
        ),
        (
            "help",
            vec![
                ("border", &p.blue, ""),
                ("chord", &p.cyan, ""),
                ("action", foreground, ""),
            ],
        ),
    ];
    for (section, styles) in groups {
        let _ = writeln!(out, "\n[{section}]");
        for (name, fg, bg) in styles {
            if bg.is_empty() {
                let _ = writeln!(out, "{name} = {{ fg = {fg:?} }}");
            } else {
                let _ = writeln!(out, "{name} = {{ fg = {fg:?}, bg = {bg:?} }}");
            }
        }
    }
    // Accent-filled controls get their own contrasting foreground, including
    // light palettes. Do not replace personal icon or file-matching rules.
    let mut doc: toml_edit::DocumentMut = out.parse().expect("generated styles");
    for (section, controls) in [
        (
            "mgr",
            vec![
                ("count_copied", p.green.as_str()),
                ("count_cut", &p.red),
                ("count_selected", &p.yellow),
            ],
        ),
        ("tabs", vec![("active", &p.blue), ("inactive", surface)]),
        (
            "mode",
            vec![
                ("normal_main", &p.blue),
                ("normal_alt", surface),
                ("select_main", &p.green),
                ("select_alt", surface),
                ("unset_main", &p.red),
                ("unset_alt", surface),
            ],
        ),
        (
            "indicator",
            vec![
                ("parent", selected),
                ("current", selected),
                ("preview", selected),
            ],
        ),
        ("confirm", vec![("btn_yes", &p.green), ("btn_no", surface)]),
        ("spot", vec![("tbl_cell", selected)]),
        ("pick", vec![("active", selected)]),
        ("input", vec![("selected", selected)]),
        ("cmp", vec![("active", selected)]),
        ("tasks", vec![("hovered", selected)]),
        ("help", vec![("hovered", selected)]),
    ] {
        // Use dotted keys on the document model to merge each existing table.
        if !doc.contains_key(section) {
            doc[section] = toml_edit::table();
        }
        for (key, bg) in controls {
            let mut style = toml_edit::InlineTable::new();
            style.insert("fg", contrast(bg).into());
            style.insert("bg", bg.into());
            doc[section][key] = toml_edit::value(style);
        }
    }
    out = doc.to_string();
    let _ = writeln!(out, "\n[filetype]\nrules = [\n  {{ mime = \"image/*\", fg = {:?} }},\n  {{ mime = \"{{audio,video}}/*\", fg = {:?} }},\n  {{ url = \"*/\", fg = {:?} }},\n  {{ url = \"*\", fg = {:?} }},\n]", p.yellow, p.magenta, p.blue, p.foreground);
    let xml = super::super::bat::tmtheme::render_tmtheme(p, &theme.id);
    let (_, rest) = xml.split_once('\n').expect("XML declaration");
    Ok((out, format!("{XML_HEADER}{rest}")))
}
