//! Saved intent, candidate discovery and generated bytes are separate evidence.
//! No font engine, cache builder, terminal, package manager or writer is invoked.
use super::Report;
use crate::adapter::font::references::{self, State, Terminal};
use crate::{
    adapter::{
        font::{FontAdapter, FontScanReport},
        font_config,
    },
    config::{
        file_read::{self, Links, Source, MAX_STATE_BYTES, MAX_TOOL_CONFIG_BYTES},
        recovery_paths,
    },
    env::SlateEnv,
    error::{Result, SlateError},
    platform::fonts,
};
use serde::Serialize;
use std::path::Path;

#[derive(Serialize)]
pub(super) struct Inventory {
    candidate_source: &'static str,
    backend: &'static str,
    selected_family: Option<String>,
    scan_complete: bool,
    nerd_family_count: usize,
    system_family_count: usize,
    reported_issue_count: usize,
    omitted_issue_count: usize,
}

#[derive(Serialize)]
pub(super) struct ReferenceSummary {
    terminal: Terminal,
    managed_path: String,
    managed_path_is_lossy: bool,
    state: State,
    inspection_complete: bool,
    entries: Vec<EntrySummary>,
    #[serde(skip_serializing_if = "Option::is_none")]
    path_error: Option<String>,
}
#[derive(Serialize)]
struct EntrySummary {
    path: String,
    path_is_lossy: bool,
    state: State,
    #[serde(skip_serializing_if = "Option::is_none")]
    reason: Option<String>,
}

impl From<references::References> for ReferenceSummary {
    fn from(observed: references::References) -> Self {
        Self {
            terminal: observed.terminal,
            managed_path: observed.managed.display().to_string(),
            managed_path_is_lossy: observed.managed.to_str().is_none(),
            state: observed.state(),
            inspection_complete: observed.inspection_complete(),
            entries: observed
                .entries
                .into_iter()
                .map(|entry| EntrySummary {
                    path: entry.path.display().to_string(),
                    path_is_lossy: entry.path.to_str().is_none(),
                    state: entry.state,
                    reason: entry.reason,
                })
                .collect(),
            path_error: observed.path_error,
        }
    }
}

fn entry_references(report: &mut Report, env: &SlateEnv) {
    let mut summaries = Vec::new();
    for observed in references::inspect(env) {
        let name = observed.terminal.name();
        let state = observed.state();
        let (code, status, message, suggestion) = match state {
            State::Found => ("font_ref_found", "ok", "direct managed-font reference observed; not an effective-font verdict", "Review later overrides and nested includes if the terminal still differs."),
            State::NotFound => ("font_ref_not_found", "warning", "no direct managed-font reference observed in the inspected entry files", "A nested or relative include may still connect the font. Review the entry chain or preview a named selection with `slate font <name> --dry-run` before applying."),
            State::Missing => ("font_ref_entry_missing", "info", "no optional entry files are present; this may be an unused terminal", "Font selection does not create an absent terminal entry. Review the terminal's configuration or use setup when you want to enable an integration."),
            State::Uninspectable => ("font_ref_unknown", "warning", "direct reference status is unknown because an entry/path could not be inspected", "Resolve the reported access/format/path issue before inferring a missing include; no repair or installation was attempted."),
        };
        report.add_code(
            code,
            status,
            format!("{name}: {message}"),
            &observed.managed,
            Some(suggestion.into()),
        );
        for entry in &observed.entries {
            match entry.state {
                State::Found => report.add_code("font_ref_entry_found", "ok", format!("{name}: literal managed-font reference observed in this entry"), &entry.path, None),
                State::NotFound => report.add_code("font_ref_entry_not_found", "info", format!("{name}: no literal direct managed-font reference in this entry; indirect paths are not checked"), &entry.path, None),
                State::Uninspectable => report.add_code("font_ref_entry_unreadable", "warning", format!("{name}: {}", entry.reason.as_deref().unwrap_or("entry could not be inspected")), &entry.path, Some("Entry reads follow regular file links and are limited to 8 MiB; isolated SLATE_HOME rejects outside targets. No referenced files or native tools are loaded.".into())),
                _ => {},
            }
        }
        if let Some(error) = &observed.path_error {
            report.add_code(
                "font_ref_paths_unreadable",
                "warning",
                format!("{name}: entry paths could not be selected: {error}"),
                &observed.managed,
                None,
            );
        }
        summaries.push(observed.into());
    }
    report.font_references = Some(summaries);
}

const CHOOSE: &str = "Use `slate font --list` to inspect candidates, then `slate font` to choose a family; this diagnostic does not select or install one.";
const REVIEW_OUTPUT: &str = "Review manual changes first. To reapply your choice, use `slate font` after resolving scan issues; it may install a selected missing catalog font. Check the terminal's includes and overrides separately.";

fn read(env: &SlateEnv, path: &Path, limit: u64) -> Result<Option<Source>> {
    recovery_paths::validate_file_path(env, path, "Font")?;
    file_read::read(path, limit, Links::Reject)
        .map_err(|error| SlateError::ConfigReadError(path.display().to_string(), error.to_string()))
}

fn saved_family(report: &mut Report, env: &SlateEnv) -> Option<String> {
    let path = env.managed_file("current-font");
    let source = match read(env, &path, MAX_STATE_BYTES) {
        Ok(Some(source)) => source,
        Ok(None) => {
            report.add_code(
                "family_unset",
                "info",
                "No saved font family; no default is assumed",
                &path,
                Some(CHOOSE.into()),
            );
            return None;
        }
        Err(error) => {
            report.add_code("family_unreadable", "error", format!("Cannot inspect saved font family: {error}"), &path,
                Some("Inspect links, permissions and the 4 KiB regular-file limit. File contents are omitted.".into()));
            return None;
        }
    };
    let Ok(value) = std::str::from_utf8(&source.bytes) else {
        report.add_code(
            "family_invalid",
            "error",
            "Saved font family is not UTF-8; file contents omitted",
            &path,
            Some(CHOOSE.into()),
        );
        return None;
    };
    let family = value.trim();
    if family.is_empty() {
        report.add_code(
            "family_unset",
            "info",
            "Saved font family is empty; no default is assumed",
            &path,
            Some(CHOOSE.into()),
        );
        return None;
    }
    if font_config::validate_family(family).is_err() {
        report.add_code(
            "family_invalid",
            "error",
            "Saved font family fails Slate's length/character rules; file contents omitted",
            &path,
            Some(CHOOSE.into()),
        );
        return None;
    }
    report.add_code(
        "family_valid",
        "ok",
        format!("Saved font family: {family}"),
        &path,
        None,
    );
    if source.bytes != family.as_bytes() {
        report.add_code(
            "family_noncanonical",
            "info",
            "Saved family is recognized after trimming whitespace; original bytes are unchanged",
            &path,
            None,
        );
    }
    Some(family.to_owned())
}

fn inventory(report: &mut Report, env: &SlateEnv, family: Option<&str>, scan: &FontScanReport) {
    let user_fonts = fonts::user_font_dir(env);
    report.add_code(if scan.is_complete() { "scan_complete" } else { "scan_incomplete" },
        if scan.is_complete() { "info" } else { "warning" },
        format!("Candidate scan {}: {} Nerd Font and {} whitelisted system families; filename/signature evidence only",
            if scan.is_complete() { "completed" } else { "is incomplete" }, scan.fonts.nerd_fonts.len(), scan.fonts.system_fonts.len()),
        &user_fonts, (!scan.is_complete()).then(|| "Inspect reported paths and scan limits before inferring absence or reinstalling. Positively observed candidates remain usable.".into()));
    for issue in &scan.issues {
        report.add_code("scan_issue", "warning", issue.reason, &issue.path,
            Some("Inspect directory access, broken links and the stated limit; no automatic repair was attempted.".into()));
    }
    if scan.omitted_issues > 0 {
        report.add_code(
            "scan_issues_omitted",
            "warning",
            format!(
                "{} additional scan issues omitted from the bounded report",
                scan.omitted_issues
            ),
            &user_fonts,
            None,
        );
    }
    if let Some(family) = family {
        let key = FontAdapter::family_match_key(family);
        let matched = scan
            .fonts
            .nerd_fonts
            .iter()
            .chain(&scan.fonts.system_fonts)
            .any(|candidate| FontAdapter::family_match_key(candidate) == key);
        let (code, status, message, suggestion) = if matched {
            ("family_candidate_found", "ok", "A filename-derived candidate matches the saved family; native matching and glyph coverage are not verified",
                "If the terminal differs, review its include chain, overrides and effective family; a candidate match does not prove font activation.")
        } else if !scan.is_complete() {
            ("family_availability_unknown", "warning", "No matching candidate was observed in an incomplete scan; availability is unknown",
                "Resolve scan issues before deciding whether installation is needed. Do not reinstall based on this result alone.")
        } else {
            ("family_candidate_not_found", "warning", "No matching candidate was found in Slate's supported filename search; this is not proof the font is uninstalled",
                "Check the reported roots, filename-derived naming, system-family whitelist and native font configuration before choosing or installing a font.")
        };
        report.add_code(
            code,
            status,
            message,
            &env.managed_file("current-font"),
            Some(suggestion.into()),
        );
    }
    report.font_inventory = Some(Inventory {
        candidate_source: "filename_and_sfnt_signature",
        backend: fonts::backend().label(),
        selected_family: family.map(str::to_owned),
        scan_complete: scan.is_complete(),
        nerd_family_count: scan.fonts.nerd_fonts.len(),
        system_family_count: scan.fonts.system_fonts.len(),
        reported_issue_count: scan.issues.len(),
        omitted_issue_count: scan.omitted_issues,
    });
}

fn outputs(report: &mut Report, env: &SlateEnv, family: Option<&str>) {
    type Renderer = fn(&str) -> Result<String>;
    // Use the same terminal-specific serializers as actual font/theme writers.
    let files: [(&str, &str, Renderer); 3] = [
        ("Ghostty", "managed/ghostty/font.conf", font_config::ghostty),
        (
            "Alacritty",
            "managed/alacritty/font.toml",
            font_config::alacritty,
        ),
        ("Kitty", "managed/kitty/font.conf", font_config::kitty),
    ];
    for (tool, relative, render) in files {
        let path = env.managed_file(relative);
        let source = match read(env, &path, MAX_TOOL_CONFIG_BYTES) {
            Ok(Some(source)) => source,
            Ok(None) => {
                report.add_code("output_missing", "info", format!("{tool} font output is missing; this may be normal for an unused integration"), &path, None);
                continue;
            }
            Err(error) => {
                report.add_code("output_unreadable", "error", format!("Cannot inspect {tool} font output: {error}"), &path,
                    Some("Inspect this path and its parents; final links, non-regular files, files over 8 MiB and paths escaping an isolated profile are not read.".into()));
                continue;
            }
        };
        let expected = family.map(render).transpose();
        match expected {
            Ok(Some(expected)) if source.bytes == expected.as_bytes() => report.add_code("output_matches", "ok", format!("{tool} font output matches Slate's generated bytes for the saved family; review the separate entry-reference checks, not a runtime verdict"), &path, None),
            Ok(Some(_)) => report.add_code("output_differs", "warning", format!("{tool} font output differs from Slate's generated bytes; this is not a syntax or runtime validity judgment"), &path, Some(REVIEW_OUTPUT.into())),
            Ok(None) => report.add_code("output_uncompared", "info", format!("{tool} font output is readable, but no valid saved family is available for comparison"), &path, Some(CHOOSE.into())),
            Err(_) => report.add_code("output_uncompared", "error", format!("Cannot render the saved family for {tool}; file contents omitted"), &path, Some(CHOOSE.into())),
        }
    }
}

pub(super) fn inspect(report: &mut Report, env: &SlateEnv) {
    report.scope = "Read-only saved-family, bounded filename/signature discovery, exact-byte generated-file checks and direct entry references. Valid saved family names are shown; invalid state and configuration contents are omitted. Search covers Nerd Font names and a platform system-family whitelist, not every font. Ordinary font links may be followed outside search roots; standard system roots remain in isolated profiles. Entry reads follow regular file links; isolated SLATE_HOME rejects outside targets. Each entry is capped at 8 MiB. No tool is launched, cache refreshed, font installed or configuration changed. Direct checks compare literal managed paths; a positive entry remains reportable when another entry is unreadable. Check each font_references inspection_complete before using absence. Internal font names, glyph coverage, native registration/matching, recursive include chains, relative/variable includes, cross-file resets, overrides, whole-file native validation and live rendering are not verified. Files are observed separately; concurrent changes and filesystem stalls are not excluded.";
    if env.session().is_isolated() {
        report.add_code("isolated_profile", "info", "Saved settings use SLATE_HOME and ignore external XDG overrides; standard system-font roots are still inspected read-only", env.home(), None);
    }
    if env.session().is_remote() {
        report.add_code("remote_session", "info", "Fonts and settings belong to this remote host, not the SSH client's terminal", env.home(),
            Some("Inspect and select the font on the client computer too; a remote font installation cannot configure the client terminal.".into()));
    }
    let family = saved_family(report, env);
    inventory(
        report,
        env,
        family.as_deref(),
        &FontAdapter::scan_fonts_with_env(env),
    );
    outputs(report, env, family.as_deref());
    entry_references(report, env);
    let user_fonts = fonts::user_font_dir(env);
    report.add_code(
        "user_font_directory",
        "info",
        format!(
            "Selected user-font directory ({}); no write-readiness or cache test was run",
            fonts::backend().label()
        ),
        &user_fonts,
        None,
    );
    for path in fonts::font_search_paths(env) {
        report.add_code(
            "search_root",
            "info",
            "Configured font search root (optional); scan problems are listed separately",
            &path,
            None,
        );
    }
    report.add_code("native_status_unchecked", "info", "No native font matching, activation or cache-refresh history was checked", &user_fonts,
        Some("Inspect any warnings from the original font installation separately; this report does not prescribe a restart or reinstall.".into()));
}

#[cfg(test)]
#[path = "font_tests.rs"]
mod tests;
