//! Inspect saved intent and generated bytes, without inferring live appearance.
use super::Report;
use crate::config::file_read::{self, Links, Source, MAX_STATE_BYTES, MAX_TOOL_CONFIG_BYTES};
use crate::config::recovery_paths;
use crate::env::SlateEnv;
use crate::error::{Result, SlateError};
use crate::opacity::{OpacityPreset, MANAGED_FILES};
use std::path::Path;

const CHOOSE_PRESET: &str = "Choose solid, frosted or clear explicitly with `slate config set opacity <preset>` if you want Slate to manage opacity; no default is assumed here.";

fn read(env: &SlateEnv, path: &Path, limit: u64) -> Result<Option<Source>> {
    recovery_paths::validate_file_path(env, path, "Opacity")?;
    file_read::read(path, limit, Links::Reject)
        .map_err(|err| SlateError::ConfigReadError(path.display().to_string(), err.to_string()))
}

fn repair(preset: OpacityPreset) -> String {
    format!("Inspect manual edits and user overrides first. `slate config set opacity {}` regenerates managed files and saves a recovery point when bytes change; it does not verify effective runtime settings.", preset.to_string().to_lowercase())
}

fn saved_preset(report: &mut Report, env: &SlateEnv) -> Option<OpacityPreset> {
    let path = env.managed_file("current-opacity");
    let source = match read(env, &path, MAX_STATE_BYTES) {
        Ok(Some(source)) => source,
        Ok(None) => {
            report.add_code(
                "preset_unset",
                "warning",
                "No saved opacity preset; generated files have no comparison baseline",
                &path,
                Some(CHOOSE_PRESET.into()),
            );
            return None;
        }
        Err(error) => {
            report.add_code("preset_unreadable", "error", format!("Cannot inspect saved opacity: {error}"), &path,
                Some("Inspect the path, links, permissions and 4 KiB regular-file limit. No file contents are included in this report.".into()));
            return None;
        }
    };
    let Ok(value) = std::str::from_utf8(&source.bytes) else {
        report.add_code(
            "preset_invalid",
            "error",
            "Saved opacity is not UTF-8; file contents omitted",
            &path,
            Some(CHOOSE_PRESET.into()),
        );
        return None;
    };
    if value.trim().is_empty() {
        report.add_code(
            "preset_unset",
            "warning",
            "Saved opacity is empty; no default is assumed",
            &path,
            Some(CHOOSE_PRESET.into()),
        );
        return None;
    }
    // The parser's error contains the supplied value. Discard it rather than
    // leaking unknown/private tracking-file contents into a diagnostic report.
    let Ok(preset) = value.trim().parse::<OpacityPreset>() else {
        report.add_code(
            "preset_invalid",
            "error",
            "Saved opacity is not a recognized preset; file contents omitted",
            &path,
            Some(CHOOSE_PRESET.into()),
        );
        return None;
    };
    let canonical = preset.to_string().to_lowercase();
    report.add_code(
        "preset_valid",
        "ok",
        format!("Saved opacity preset: {canonical}"),
        &path,
        None,
    );
    if source.bytes != canonical.as_bytes() {
        report.add_code(
            "preset_noncanonical",
            "info",
            "The saved preset is recognized but not in Slate's canonical byte form",
            &path,
            Some(repair(preset)),
        );
    }
    Some(preset)
}

pub(super) fn inspect(report: &mut Report, env: &SlateEnv) {
    report.scope = "Read-only inspection of the saved opacity preset and Slate-generated files using exact-byte comparisons. Tool installation, include chains, user overrides, compositor support and live window appearance are not checked; no tool is launched or configuration changed. Missing files can be normal for unused integrations. Files are observed separately; concurrent edits can change this report.";
    if env.session().is_isolated() {
        report.add_code(
            "isolated_profile",
            "info",
            "Inspecting the isolated SLATE_HOME profile; host configuration is not used",
            env.home(),
            None,
        );
    }
    if env.session().is_remote() {
        report.add_code("remote_session", "info", "These files belong to the remote host; SSH cannot apply opacity to the client terminal", env.config_dir(), None);
    }
    let preset = saved_preset(report, env);
    for file in MANAGED_FILES {
        let path = file.path(env);
        let label = file.stage();
        match read(env, &path, MAX_TOOL_CONFIG_BYTES) {
            Err(error) => report.add_code("output_unreadable", "error", format!("Cannot inspect {label}: {error}"), &path,
                Some("Inspect this target and its parent directories; final links, non-regular files, files over 8 MiB and paths escaping an isolated profile are not read.".into())),
            Ok(None) => report.add_code("output_missing", "info", format!("{label} file is missing; this may be normal for an unused integration"), &path,
                preset.map(repair)),
            Ok(Some(source)) => match preset {
                Some(preset) if file.content_matches(preset, &source.bytes) => report.add_code("output_matches", "ok", format!("{label} matches Slate's generated bytes for the saved preset"), &path, None),
                Some(preset) => report.add_code("output_differs", "warning", format!("{label} differs from Slate's generated bytes; this is not a syntax or runtime validity judgment"), &path, Some(repair(preset))),
                None => report.add_code("output_uncompared", "info", format!("{label} is readable, but no valid saved preset is available for comparison"), &path, None),
            },
        }
    }
    let paths = crate::opacity::managed_paths(env)
        .chain(std::iter::once(env.managed_file("current-opacity")));
    match recovery_paths::targets(env, paths, "Opacity") {
        Ok(targets) if targets.len() == MANAGED_FILES.len() + 1 => report.add_code("write_path_layout", "info", "No opacity target/recovery-storage layout conflict was found; write permissions are not verified", env.config_dir(), None),
        Ok(_) => report.add_code("output_alias_conflict", "error", "Distinct terminal outputs resolve to the same file", env.config_dir(),
            Some("Separate the managed terminal directories before applying opacity.".into())),
        Err(error) => report.add_code("write_paths_blocked", "error", format!("Opacity write-path checks would block application: {error}"), env.config_dir(),
            Some("Inspect the reported path layout before applying settings. This diagnostic has not attempted a write.".into())),
    }
}
